"""SQL translation for the Postgres jobs database. No database is contacted."""

import os
import unittest
from unittest.mock import patch

from app.jobs_db import adapt_sql, postgres_enabled, translate_sql


class JobsDbSqlTests(unittest.TestCase):
    def test_unset_database_url_is_sqlite(self):
        with patch.dict(os.environ, {}, clear=False):
            os.environ.pop("DATABASE_URL", None)
            self.assertFalse(postgres_enabled())

    def test_placeholders_stay_out_of_quoted_text(self):
        self.assertEqual(
            translate_sql("SELECT id FROM jobs WHERE id = ? AND title = '?'"),
            "SELECT id FROM jobs WHERE id = %s AND title = '?'",
        )
        self.assertEqual(
            translate_sql("INSERT INTO crawl_sources (name) VALUES (:name)"),
            "INSERT INTO crawl_sources (name) VALUES (%(name)s)",
        )
        self.assertEqual(translate_sql("SELECT '100%'"), "SELECT '100%'")

    def test_postgres_ddl_and_aggregate(self):
        adapted = adapt_sql(
            "CREATE TABLE jobs (id INTEGER PRIMARY KEY, title TEXT); "
            "SELECT group_concat(js.source_name, ', ') FROM job_sources js"
        )
        self.assertIn("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", adapted)
        self.assertIn("string_agg(js.source_name, ', ')", adapted)
        self.assertNotIn("group_concat", adapted.lower())


if __name__ == "__main__":
    unittest.main()


class WantsReturningTest(unittest.TestCase):
    def test_tables_without_id_skip_returning(self):
        from app.jobs_db import _wants_returning

        self.assertTrue(_wants_returning("INSERT INTO jobs (title) VALUES (?)"))
        self.assertFalse(
            _wants_returning(
                "INSERT INTO maintenance_steps (name, done_at) VALUES (?, ?) ON CONFLICT (name) DO NOTHING"
            )
        )
        self.assertFalse(_wants_returning("INSERT INTO tidy_batch_jobs (batch_id, job_id) VALUES (?, ?)"))

