"""Jobs database connection.

SQLite is the Mac default: worker/data/jobs.sqlite, or JOBS_DB_PATH when that
variable is set. When DATABASE_URL is set in the process environment, the API
and the worker both use that Postgres database instead. A Railway volume cannot
be mounted on two services, so the deployed jobs database is Postgres, not a
shared sqlite file.

SQL in the rest of the code stays in the sqlite shape (? placeholders, INTEGER
PRIMARY KEY, PRAGMA table_info). This module translates that only on the
Postgres connection.
"""

from __future__ import annotations

import os
import re
import sqlite3
from typing import Any

_ID_PK = re.compile(r"\bid\s+integer\s+primary\s+key\b", re.IGNORECASE)
_GROUP = re.compile(r"\bgroup_concat\b", re.IGNORECASE)
_INSERT = re.compile(r"^\s*insert\s+into\s+([A-Za-z_][A-Za-z0-9_]*)\b", re.IGNORECASE)
_RETURNING = re.compile(r"\breturning\b", re.IGNORECASE)
_TABLE_INFO = re.compile(
    r"pragma\s+table_info\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)",
    re.IGNORECASE,
)


_POSTGRES_SCHEMES = ("postgresql://", "postgres://", "postgresql+", "postgres+")


def _clean_url(value: str | None) -> str:
    return (value or "").strip().strip("'\"").strip()


def postgres_enabled() -> bool:
    """True only when DATABASE_URL looks like a PostgreSQL connection string.

    Empty values, sqlite paths, and unresolved reference placeholders such as
    ${{Postgres.DATABASE_URL}} all return False.
    """
    url = _clean_url(os.environ.get("DATABASE_URL")).lower()
    return url.startswith(_POSTGRES_SCHEMES)


def schema_cache_key() -> str:
    """Process-local key so DDL / taxonomy caches do not leak across DBs."""
    if postgres_enabled():
        return "postgres"
    try:
        from app.sqlite_jobs import DB_PATH

        return str(DB_PATH)
    except Exception:
        return os.environ.get("JOBS_DB_PATH", "").strip() or "sqlite-default"


def normalize_database_url(url: str) -> str:
    raw = url.strip()
    for prefix in (
        "postgresql+psycopg2://",
        "postgresql+psycopg://",
        "postgres+psycopg://",
    ):
        if raw.startswith(prefix):
            return "postgresql://" + raw[len(prefix) :]
    if raw.startswith("postgres://"):
        return "postgresql://" + raw[len("postgres://") :]
    return raw


def translate_sql(sql: str) -> str:
    """Rewrite sqlite placeholders for psycopg. Leaves quoted text alone."""
    out: list[str] = []
    i = 0
    n = len(sql)
    in_str = False
    while i < n:
        ch = sql[i]
        if in_str:
            out.append(ch)
            if ch == "'":
                if i + 1 < n and sql[i + 1] == "'":
                    out.append("'")
                    i += 2
                    continue
                in_str = False
            i += 1
            continue
        if ch == "'":
            in_str = True
            out.append(ch)
            i += 1
            continue
        if ch == "?":
            out.append("%s")
            i += 1
            continue
        if ch == ":" and i + 1 < n and (sql[i + 1].isalpha() or sql[i + 1] == "_"):
            j = i + 1
            while j < n and (sql[j].isalnum() or sql[j] == "_"):
                j += 1
            out.append("%(" + sql[i + 1 : j] + ")s")
            i = j
            continue
        if ch == "%":
            out.append("%%")
            i += 1
            continue
        out.append(ch)
        i += 1
    return "".join(out)


def adapt_sql(sql: str) -> str:
    rewritten = _ID_PK.sub(
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        sql,
    )
    rewritten = _GROUP.sub("string_agg", rewritten)
    return translate_sql(rewritten)


def _split_script(script: str) -> list[str]:
    parts: list[str] = []
    buf: list[str] = []
    in_str = False
    i = 0
    n = len(script)
    while i < n:
        ch = script[i]
        if in_str:
            buf.append(ch)
            if ch == "'":
                if i + 1 < n and script[i + 1] == "'":
                    buf.append("'")
                    i += 2
                    continue
                in_str = False
            i += 1
            continue
        if ch == "'":
            in_str = True
            buf.append(ch)
        elif ch == ";":
            statement = "".join(buf).strip()
            if statement:
                parts.append(statement)
            buf = []
        else:
            buf.append(ch)
        i += 1
    tail = "".join(buf).strip()
    if tail:
        parts.append(tail)
    return parts


# Composite / non-integer PKs — Postgres adapter must not append RETURNING id.
_NO_ID_TABLES = {
    "academy_identities",
    "ai_cache",
    "ai_feature_flags",
    "ai_usage_daily",
    "api_usage",
    "candidate_profiles",
    "company_profiles",
    "contact_emails",
    "embeddings",
    "job_skill",
    "maintenance_steps",
    "oidc_transactions",
    "role_skill_weight",
    "skill_pair_daily",
    "skill_trend_daily",
    "tidy_batch_jobs",
}


def _wants_returning(sql: str) -> bool:
    match = _INSERT.match(sql)
    if match is None:
        return False
    if _RETURNING.search(sql):
        return False
    # Tables without an integer "id" column must not get RETURNING id.
    return match.group(1).lower() not in _NO_ID_TABLES


def _params(params: Any) -> Any:
    if params is None:
        return ()
    if isinstance(params, dict):
        return params
    if isinstance(params, (str, bytes)):
        raise TypeError("query parameters must be a sequence or a dict")
    return tuple(params)


class Row:
    def __init__(self, columns: list[str], values: tuple) -> None:
        self._columns = list(columns)
        self._values = tuple(values)
        self._map = dict(zip(self._columns, self._values))

    def __getitem__(self, key: int | str):
        if isinstance(key, int):
            return self._values[key]
        return self._map[key]

    def keys(self) -> list[str]:
        return list(self._columns)


class _Cursor:
    def __init__(self, rows: list[Row], lastrowid: int | None, rowcount: int = 0) -> None:
        self._rows = rows
        self._index = 0
        self.lastrowid = lastrowid
        self.rowcount = int(rowcount or 0)

    def fetchone(self) -> Row | None:
        if self._index >= len(self._rows):
            return None
        row = self._rows[self._index]
        self._index += 1
        return row

    def fetchall(self) -> list[Row]:
        rows = self._rows[self._index :]
        self._index = len(self._rows)
        return rows

    def __iter__(self):
        while self._index < len(self._rows):
            row = self._rows[self._index]
            self._index += 1
            yield row


def _reraise(exc: Exception) -> None:
    import psycopg

    if isinstance(exc, psycopg.IntegrityError):
        raise sqlite3.IntegrityError(str(exc)) from exc
    raise exc


class PostgresConnection:
    def __init__(self, url: str) -> None:
        import psycopg

        self.row_factory = None
        self._conn = psycopg.connect(normalize_database_url(url), connect_timeout=10)

    def execute(self, sql: str, params: Any = ()) -> _Cursor:
        info = _TABLE_INFO.search(sql)
        if info is not None:
            return self._run(
                """
                SELECT (ordinal_position - 1)::int, column_name
                FROM information_schema.columns
                WHERE table_schema = current_schema() AND table_name = %s
                ORDER BY ordinal_position
                """,
                (info.group(1),),
                returning=False,
            )
        if sql.lstrip().upper().startswith("PRAGMA"):
            return _Cursor([], None, rowcount=0)
        adapted = adapt_sql(sql)
        returning = _wants_returning(sql)
        if returning:
            adapted = adapted.rstrip().rstrip(";") + " RETURNING id"
        return self._run(adapted, _params(params), returning=returning)

    def executemany(self, sql: str, seq) -> _Cursor:
        adapted = adapt_sql(sql)
        n = 0
        try:
            with self._conn.cursor() as cur:
                cur.executemany(adapted, list(seq))
                n = int(cur.rowcount or 0)
        except Exception as exc:
            _reraise(exc)
        return _Cursor([], None, rowcount=n)

    def executescript(self, script: str) -> _Cursor:
        for statement in _split_script(script):
            self.execute(statement)
        self.commit()
        return _Cursor([], None, rowcount=0)

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()

    def close(self) -> None:
        self._conn.close()

    def __enter__(self) -> "PostgresConnection":
        return self

    def __exit__(self, exc_type, exc, tb) -> bool:
        if exc_type is None:
            self.commit()
        else:
            self.rollback()
        return False

    def _run(self, sql: str, params: Any, *, returning: bool) -> _Cursor:
        try:
            cur = self._conn.execute(sql, params)
            n = int(cur.rowcount or 0)
            if returning:
                row = cur.fetchone()
                last = int(row[0]) if row and row[0] is not None else None
                return _Cursor([], last, rowcount=n)
            if cur.description is None:
                return _Cursor([], None, rowcount=n)
            columns = [item.name for item in cur.description]
            rows = [Row(columns, tuple(item)) for item in cur.fetchall()]
            return _Cursor(rows, None, rowcount=n if n else len(rows))
        except Exception as exc:
            _reraise(exc)
        raise AssertionError("unreachable")


def connect(url: str | None = None) -> PostgresConnection:
    chosen = _clean_url(url if url is not None else os.environ.get("DATABASE_URL", ""))
    if not chosen:
        raise RuntimeError("DATABASE_URL is not set")
    return PostgresConnection(chosen)
