export const copy = {
  az: {
    lang: "az",
    browse: "Elanlara bax",
    post: "Elan yarat",
    heading: "Açıq iş elanları",
    lede: "Başlıq və ya şirkət üzrə axtarın. Şəhər varsa, siyahını ona görə daraldın.",
    ecosystemLine: "Ingress ekosisteminin bir hissəsi",
    ecosystemLinkLabel: "Ingress Academy",
    ecosystemFooter: "Ingress Job — Ingress ekosisteminin iş elanları məhsulu. Giriş Ingress Academy hesabı ilədir.",
    search: "Axtarış",
    searchPlaceholder: "Vəzifə və ya şirkət",
    openRole: "Aç",
    city: "Şəhər",
    allCities: "Bütün şəhərlər",
    count: (n) => `${n} elan`,
    pagePrev: "Əvvəlki",
    pageNext: "Növbəti",
    pageOf: (page, total) => `Səhifə ${page} / ${total}`,
    empty: "Bu süzgəcə uyğun elan yoxdur.",
    loadError: "Elanları yükləmək olmadı. API ünvanı yoxlanılmalıdır.",
    noCompany: "Şirkət göstərilməyib",
    noCity: "Şəhər göstərilməyib",
    source: "Mənbə",
    back: "Elanlara qayıt",
    breadcrumbs: "Yol izi",
    breadcrumbHome: "Elanlar",
    faq: {
      eyebrow: "Suallar",
      title: "Tez-tez verilən suallar",
      items: [
        {
          q: "Ingress Job nədir?",
          a: "Ingress Job Azərbaycanda açıq iş elanlarını bir yerdə göstərən platformadır və Ingress ekosisteminin bir hissəsidir. Vəzifə, şirkət, şəhər, dil və əməkhaqqı üzrə axtarıb süzə bilərsiniz.",
        },
        {
          q: "Ingress ilə əlaqəsi nədir?",
          a: "Ingress Job Ingress layihə ailəsinin məhsuludur. Giriş və qeydiyyat Ingress Academy hesabı ilə gedir — eyni hesab ekosistemdəki digər məhsullarda da istifadə oluna bilər.",
        },
        {
          q: "Elanlara baxmaq pulsuzdur?",
          a: "Bəli. Açıq elanları hesab olmadan da oxuya bilərsiniz. Müraciət və elan yerləşdirmə üçün Ingress Academy hesabı lazımdır.",
        },
        {
          q: "Necə axtarıb filtrləyə bilərəm?",
          a: "Başlıq və ya şirkət üzrə axtarın; şəhər, mənbə, dil, tarix, uzaqdan iş və əməkhaqqı sərhədləri ilə siyahını daraldın.",
        },
        {
          q: "Müraciət etmək üçün hesab lazımdır?",
          a: "Bəli. Namizəd kimi qeydiyyatdan keçəndən sonra elana müraciət edə və müraciətlərinizi izləyə bilərsiniz.",
        },
        {
          q: "İş elanı necə yerləşdirilir?",
          a: "İşəgötürən kimi qeydiyyatdan keçin, şirkət profilini doldurun və elanı yazın. Dərcdən əvvəl elan moderasiyadan keçir.",
        },
        {
          q: "Uzaqdan iş elanları varmı?",
          a: "Bəli. Uzaqdan və ya şəhəri göstərilməyən elanları filtrlə seçə bilərsiniz; hibrid və ofis elanları da siyahıdadır.",
        },
        {
          q: "Elanlar haradan gəlir?",
          a: "Siyahıda həm platformada yazılmış elanlar, həm də toplanmış açıq mənbə elanları ola bilər. Hər elanda mənbə göstərilir.",
        },
        {
          q: "Hansı dillərdə istifadə edə bilərəm?",
          a: "Sayt Azərbaycan, İngilis və Rus dillərindədir. Elanın öz dili fərqli ola bilər — dil filtrindən istifadə edin.",
        },
      ],
    },
    apply: "Müraciət et",
    original: "Orijinal elan",
    locked: "Hesab tələb olunur. Ünvan burada göstərilmir.",
    missing: "Elan tapılmadı.",
    postTitle: "İşəgötürən kabineti",
    postBody: "Elan yazmaq üçün qeydiyyatdan keçin.",
    description: "Təsvir",
    sources: "Mənbə",
    companies: "Şirkət",
    companyPlaceholder: "Şirkət adı",
    inDescription: "Təsvirin içində də axtar",
    withCity: "Yalnız şəhəri olanlar",
    remote: "Uzaqdan və ya şəhərsiz",
    relocationFilter: "Relokasiya və ya viza dəstəyi",
    relocationBadge: "Relokasiya / viza",
    techStack: "Texnologiyalar",
    techPlaceholder: "Texnologiya axtarın",
    sourceSite: "Mənbə saytı",
    salaryFilter: "Əməkhaqqı",
    salaryMin: "Minimum",
    salaryMax: "Maksimum",
    salaryNote: "Razılaşma ilə olanlar da daxildir",
    clear: "Filtrləri təmizlə",
    filters: "Filtrlər",
    sort: "Sıra",
    newest: "Ən yeni",
    oldest: "Ən köhnə",
    byTitle: "Başlığa görə",
    when: "Tarix",
    anyTime: "Hamısı",
    today: "Bu gün",
    week: "Son 7 gün",
    language: "Elanın dili",
    langAz: "Azərbaycan",
    langEn: "İngilis",
        langRu: "Rus",
    register: "Qeydiyyat",
    registerAsk: "Ingress Academy hesabı ilə: elan paylaşan, yoxsa müraciət edən?",
    registerPoster: "Elan paylaşan",
    registerCreator: "Müraciət edən",
    signOut: "Çıxış",
    roleEmployer: "İşəgötürən",
    roleCandidate: "Namizəd",
    roleStaff: "Əməkdaş",
    companyTitle: "Şirkət profili",
    companyLede: "Elan yerləşdirməzdən əvvəl şirkət adı, şəhər və qısa təsvir saxlanmalıdır.",
    companyName: "Şirkət adı",
    companyCity: "Şəhər",
    companyAbout: "Qısa təsvir",
    companySave: "Saxla",
    companyRequired: "Şirkət adı, şəhər və qısa təsvir doldurulmalıdır.",
    companySaved: "Şirkət profili saxlanıldı.",
    ssoError: "Giriş alınmadı. Yenidən cəhd edin.",
    account: "Hesab",
    cabinetLede: "Öz elanlarınızı yazın, redaktə edin və bağlayın. Şirkət elanı təsdiqə qədər ictimai siyahıda görünmür. Dərcdən sonra başlıq, mətn, şirkət, şəhər və ya dil dəyişəndə elan yenidən moderasiyaya düşür.",
    cabinetEmpty: "Hələ elanınız yoxdur.",
    newAd: "Yeni elan",
    editAd: "Elanı redaktə et",
    myAds: "Elanlarım",
    adTitle: "Başlıq",
    adBody: "Mətn",
    adSalary: "Əməkhaqqı",
    adOptional: "İstəyə bağlı",
    adJobType: "İş növü",
    adJobTypeNone: "Seçilməyib",
    jobOffice: "Ofis",
    jobHybrid: "Hibrid",
    jobRemoteType: "Uzaqdan",
    placeRemote: "Uzaqdan",
    adCityOrRemote: "Şəhər və ya uzaqdan",
    adSave: "Saxla",
    adClose: "Bağla",
    adCloseAsk: "Elan bağlansın? İctimai siyahıdan çıxacaq.",
    adEdit: "Redaktə",
    adCancel: "Ləğv et",
    adRequired: "Başlıq, şirkət, şəhər və ya uzaqdan, və mətn doldurulmalıdır.",
    adSavedPending: "Elan moderasiyaya göndərildi.",
    adSavedLive: "Elan dərc olundu.",
    adClosedNote: "Elan bağlandı.",
    statusPending: "Moderasiyada",
    statusPublished: "Dərc olunub",
    statusClosed: "Bağlanıb",
    companyLocked: "Şirkət adı saxlanmış profildən gəlir.",
    cannotEdit: "Təsdiqlənmiş elan dəyişdirilə bilməz.",
    cabinetError: "Elanı saxlamaq olmadı.",
    statusRejected: "Rədd edilib",
    admin: "Moderasiya",
    adminTitle: "Elan moderasiyası",
    adminLede: "Gözləyən elanları səbəblə rədd edin, təsdiqləyin və ya bağlayın. Toplanmış elanları redaktə edin, gizlədin və ya birləşdirin.",
    adminGate: "Moderasiya yalnız əməkdaş hesabı üçündür.",
    adminQueue: "Elan növbəsi",
    adminEmpty: "Moderasiya üçün elan yoxdur.",
    adminApprove: "Təsdiqlə",
    adminReject: "Rədd et",
    adminRejectAsk: "Rədd səbəbini yazın. Boş saxlasanız, elan rədd edilməyəcək.",
    adminApprovedNote: "Elan dərc olundu.",
    adminRejectedNote: "Elan rədd edildi.",
    adminSavedNote: "Dəyişikliklər saxlanıldı.",
    adminError: "Əməliyyat alınmadı.",
    rejectReason: "Rədd səbəbi",
    rejectReasonRequired: "Rədd səbəbi yazılmalıdır.",
    resubmitHint: "Rədd edilmiş elanı saxlayanda o yenidən moderasiyaya düşür və ictimai siyahıdan kənarda qalır.",
    reviewHint: "Başlıq, mətn, şirkət, şəhər, uzaqdan və ya dil dəyişəndə elan yenidən moderasiyaya düşür. Yalnız əməkhaqqı və iş növü dərcdə qalır.",
    cannotChange: "Bu elan dəyişdirilə bilməz.",
    collectedTitle: "Toplanmış elanlar",
    collectedLede: "Avtomatik toplanmış elanı redaktə edin, ictimai saytdan gizlədin və ya iki dublikatı birləşdirin.",
    collectedEmpty: "Toplanmış elan yoxdur.",
    collectedHide: "Gizlət",
    collectedShow: "Göstər",
    collectedHidden: "Gizlədilib",
    collectedKeep: "Saxlanılan budur",
    collectedMerge: "Dublikatı gizlət",
    collectedMerged: "Birləşdirilib",
    collectedMergeNote: "Dublikat gizlədildi. Saxlanılan elan görünür.",
    collectedHideNote: "Elan ictimai saytdan gizlədildi.",
    collectedShowNote: "Elan yenidən ictimai siyahıdadır.",
    collectedKept: "Saxlanılan elan seçildi.",
    manualTitle: "Əl ilə mənbə keçidi",
    manualLede: "Avtomatik toplanmayan elanı, məsələn LinkedIn, məcburi sahələr və orijinal ünvanla əlavə edin. Qonaq ünvanı görmür.",
    manualUrl: "Orijinal ünvan",
    manualSaved: "Elan dərc olundu. Ünvan yalnız qeydiyyatdan sonra açılır.",
    manualUrlInvalid: "Orijinal ünvan http və ya https olmalıdır.",
    applyMessage: "Qısa müraciət",
    applyCv: "CV",
    applyCvHint: "PDF, DOC və ya DOCX, ən çox 5 MB.",
    applySend: "Müraciəti göndər",
    applySent: "Müraciət göndərildi.",
    applyRequired: "Qısa müraciət yazılmalıdır.",
    applyDuplicate: "Bu elana artıq müraciət etmisiniz.",
    applyError: "Müraciət göndərilmədi.",
    myApplications: "Müraciətlərim",
    applicationsTitle: "Müraciətlər",
    applicationsEmpty: "Hələ müraciət yoxdur.",
    downloadCv: "CV-ni aç",
    noCv: "CV yoxdur",
    ownerApplications: "Bu elana müraciətlər",
    applyPhone: "Telefon",
    applyEmail: "E-poçt",
    applyFieldRequired: "Məcburi sahələr doldurulmalıdır.",
    applyPhoneInvalid: "Telefon nömrəsi düzgün deyil.",
    applyEmailInvalid: "E-poçt düzgün deyil.",
    applyCvRequired: "CV faylı PDF, DOC və ya DOCX olmalıdır və 5 MB-dan böyük ola bilməz.",
    formTitle: "Müraciət forması",
    formLede: "Namizəd yalnız seçilmiş sahələri doldurur. Hər sahə məcburi və ya istəyə bağlı ola bilər. Ən çox 5 öz sualı. Formanı dərcdən sonra da dəyişmək olar; köhnə müraciətlər öz cavabını saxlayır.",
    fieldRequired: "Məcburi",
    formQuestion: "Öz sualı",
    formAddQuestion: "Sual əlavə et",
    formRemoveQuestion: "Sil",
    formNeedField: "Ən azı bir sahə seçilməlidir.",
    formQuestionNeeded: "Sual yazılmalıdır.",
    appSubmitted: "göndərildi",
    appSeen: "baxıldı",
    appRejected: "rədd edildi",
    appWithdraw: "Müraciəti geri götür",
    appWithdrawAsk: "Müraciət geri götürülsün? Sonra yenidən müraciət etmək olar.",
    appSeenAction: "Baxıldı",
    appRejectAction: "Rədd et",
    appRejectAsk: "Rədd səbəbi istəyə bağlıdır. Boş saxlasanız, namizəd səbəb görməyəcək.",
    appUpdated: "Status yeniləndi.",
    appWithdrawn: "Müraciət geri götürüldü.",
    appStatusError: "Statusu dəyişmək olmadı.",
    myApplicationsLede: "Bu saytda göndərdiyiniz müraciətlər. Status: göndərildi, baxıldı və ya rədd edildi.",
    applicationsGate: "Müraciətlər namizəd hesabı tələb edir.",
    languageAuto: "Avtomatik",
    profileTitle: "Profil",
    profileLede: "Bu məlumatlar job saytında saxlanır. Academy hesab ayarları açılmır.",
    profileOpen: "Profili aç",
    profileCompanyLede: "Şirkət adı, şəhər və qısa təsvir. Saxlayanda profil yenilənir.",
    profileApplicantTitle: "Namizəd profili",
    profileApplicantLede: "Görünən ad, telefon və e-poçt job saytında qalır. Müraciət forması telefon və ya e-poçt istəsə və sahə boşdursa, buradan doldurulur. Həmin müraciətdə dəyişmək olar.",
    profileName: "Görünən ad",
    profileNameRequired: "Görünən ad yazılmalıdır.",
    profileSaved: "Profil saxlanıldı.",
    profileGate: "Profil işəgötürən, namizəd və ya əməkdaş hesabı üçündür.",
    notifications: "Bildirişlər",
    notificationsTitle: "Bildirişlər",
    notificationsEmpty: "Bildiriş yoxdur.",
    notificationsGate: "Bildirişlər üçün hesaba daxil olun.",
    notificationsUnread: (n) => `Bildirişlər, ${n} oxunmamış`,
    markRead: "Oxundu",
    markAllRead: "Hamısını oxunmuş et",
    noteApplicationNew: (title) => `«${title}» elanına yeni müraciət gəldi.`,
    noteApplicationSeen: (title) => `«${title}» elanına müraciətinizə baxıldı.`,
    noteApplicationRejected: (title) => `«${title}» elanına müraciətiniz rədd edildi.`,
    noteAdApproved: (title) => `«${title}» elanınız təsdiqləndi.`,
    noteAdRejected: (title) => `«${title}» elanınız rədd edildi.`,
    noteAdReview: (title) => `«${title}» elanınız dəyişiklikdən sonra yenidən moderasiyadadır.`,


  },
  en: {
    lang: "en",
    browse: "Browse jobs",
    post: "Post a job",
    heading: "Open roles",
    lede: "Search by title or company. Narrow the list by city when a city is listed.",
    ecosystemLine: "Part of the Ingress ecosystem",
    ecosystemLinkLabel: "Ingress Academy",
    ecosystemFooter: "Ingress Job is the job board in the Ingress ecosystem. Sign-in uses your Ingress Academy account.",
    search: "Search",
    searchPlaceholder: "Title or company",
    openRole: "Open",
    city: "City",
    allCities: "All cities",
    count: (n) => `${n} ${n === 1 ? "job" : "jobs"}`,
    pagePrev: "Previous",
    pageNext: "Next",
    pageOf: (page, total) => `Page ${page} / ${total}`,
    empty: "No roles match this filter.",
    loadError: "Jobs could not be loaded. Check that the API is running.",
    noCompany: "Company not listed",
    noCity: "City not listed",
    source: "Source",
    back: "Back to jobs",
    breadcrumbs: "Breadcrumb",
    breadcrumbHome: "Jobs",
    faq: {
      eyebrow: "Questions",
      title: "Common questions",
      items: [
        {
          q: "What is Ingress Job?",
          a: "Ingress Job is a board of open roles in Azerbaijan and part of the Ingress ecosystem. Search and filter by title, company, city, language, and salary.",
        },
        {
          q: "How does it relate to Ingress?",
          a: "Ingress Job is a product in the Ingress family. Sign-in and registration use your Ingress Academy account — the same account can work across other products in the ecosystem.",
        },
        {
          q: "Is browsing free?",
          a: "Yes. You can read open listings without an account. Applying and posting require an Ingress Academy account.",
        },
        {
          q: "How do I search and filter?",
          a: "Search by title or company, then narrow the list by city, source, language, date, remote work, and salary range.",
        },
        {
          q: "Do I need an account to apply?",
          a: "Yes. Register as a candidate to apply to a role and track your applications.",
        },
        {
          q: "How do I post a job?",
          a: "Register as an employer, save your company profile, then write the ad. Listings go through moderation before they go public.",
        },
        {
          q: "Are remote jobs included?",
          a: "Yes. You can filter for remote or city-less roles; hybrid and office listings are in the list too.",
        },
        {
          q: "Where do listings come from?",
          a: "The board may include ads written on the platform and open listings gathered from other sources. Each job shows its source.",
        },
        {
          q: "Which languages can I use?",
          a: "The site is available in Azerbaijani, English, and Russian. A listing’s own language may differ — use the language filter.",
        },
      ],
    },
    apply: "Apply",
    original: "Original listing",
    locked: "An account is required. The address is not shown here.",
    missing: "This job was not found.",
    postTitle: "Employer cabinet",
    postBody: "Register to write a job ad.",
    description: "Description",
    sources: "Source",
    companies: "Company",
    companyPlaceholder: "Company name",
    inDescription: "Also search the description",
    withCity: "Only jobs with a city",
    remote: "Remote or no city",
    relocationFilter: "Relocation or visa support",
    relocationBadge: "Relocation / visa",
    techStack: "Tech stack",
    techPlaceholder: "Find a technology",
    sourceSite: "Source site",
    salaryFilter: "Salary",
    salaryMin: "Minimum",
    salaryMax: "Maximum",
    salaryNote: "Includes negotiable / by agreement",
    clear: "Clear filters",
    filters: "Filters",
    sort: "Sort",
    newest: "Newest",
    oldest: "Oldest",
    byTitle: "By title",
    when: "Date",
    anyTime: "Any time",
    today: "Today",
    week: "Last 7 days",
    language: "Listing language",
    langAz: "Azerbaijani",
    langEn: "English",
        langRu: "Russian",
    register: "Register",
    registerAsk: "With an Ingress Academy account: posting a job, or applying?",
    registerPoster: "Posting a job",
    registerCreator: "Applying",
    signOut: "Sign out",
    roleEmployer: "Employer",
    roleCandidate: "Candidate",
    roleStaff: "Staff",
    companyTitle: "Company profile",
    companyLede: "Save the company name, city, and a short description before posting.",
    companyName: "Company name",
    companyCity: "City",
    companyAbout: "Short description",
    companySave: "Save",
    companyRequired: "Company name, city, and a short description are required.",
    companySaved: "Company profile saved.",
    ssoError: "Sign-in did not finish. Try again.",
    account: "Account",
    cabinetLede: "Write, edit, and close your own ads. A company ad stays off the public list until it is approved. After publication, a change to the title, text, company, city, or language sends it back to moderation.",
    cabinetEmpty: "You have no ads yet.",
    newAd: "New ad",
    editAd: "Edit ad",
    myAds: "My ads",
    adTitle: "Title",
    adBody: "Text",
    adSalary: "Salary",
    adOptional: "Optional",
    adJobType: "Job type",
    adJobTypeNone: "Not selected",
    jobOffice: "Office",
    jobHybrid: "Hybrid",
    jobRemoteType: "Remote",
    placeRemote: "Remote",
    adCityOrRemote: "City or remote",
    adSave: "Save",
    adClose: "Close",
    adCloseAsk: "Close this ad? It leaves the public list.",
    adEdit: "Edit",
    adCancel: "Cancel",
    adRequired: "Title, company, city or remote, and the text are required.",
    adSavedPending: "The ad was sent for moderation.",
    adSavedLive: "The ad is published.",
    adClosedNote: "The ad is closed.",
    statusPending: "In moderation",
    statusPublished: "Published",
    statusClosed: "Closed",
    companyLocked: "The company name comes from the saved profile.",
    cannotEdit: "An approved ad can no longer be edited.",
    cabinetError: "The ad could not be saved.",
    statusRejected: "Rejected",
    admin: "Moderation",
    adminTitle: "Ad moderation",
    adminLede: "Reject pending ads with a reason, or approve and close them. Edit, hide, or merge collected ads.",
    adminGate: "Moderation is only for staff accounts.",
    adminQueue: "Ad queue",
    adminEmpty: "There are no ads to moderate.",
    adminApprove: "Approve",
    adminReject: "Reject",
    adminRejectAsk: "Write the rejection reason. If you leave it empty, the ad is not rejected.",
    adminApprovedNote: "The ad is published.",
    adminRejectedNote: "The ad was rejected.",
    adminSavedNote: "Changes saved.",
    adminError: "The action could not be completed.",
    rejectReason: "Rejection reason",
    rejectReasonRequired: "A rejection reason is required.",
    resubmitHint: "Saving a rejected ad sends it back to moderation and keeps it off the public list.",
    reviewHint: "Changing the title, text, company, city, remote flag, or language sends the ad back to moderation. Salary and job type alone stay published.",
    cannotChange: "This ad can no longer be changed.",
    collectedTitle: "Collected ads",
    collectedLede: "Edit an automatically collected ad, hide it from the public site, or merge two duplicates.",
    collectedEmpty: "There are no collected ads.",
    collectedHide: "Hide",
    collectedShow: "Show",
    collectedHidden: "Hidden",
    collectedKeep: "Keep this one",
    collectedMerge: "Hide as duplicate",
    collectedMerged: "Merged",
    collectedMergeNote: "The duplicate is hidden. The kept ad stays visible.",
    collectedHideNote: "The ad is hidden from the public site.",
    collectedShowNote: "The ad is on the public list again.",
    collectedKept: "Kept ad selected.",
    manualTitle: "Manual source link",
    manualLede: "Add an ad that was not collected automatically, such as LinkedIn, with the required fields and the original URL. Guests never see that URL.",
    manualUrl: "Original URL",
    manualSaved: "The ad is published. The URL opens only after registration.",
    manualUrlInvalid: "The original URL must be http or https.",
    applyMessage: "Short message",
    applyCv: "CV",
    applyCvHint: "PDF, DOC, or DOCX, up to 5 MB.",
    applySend: "Send application",
    applySent: "Application sent.",
    applyRequired: "A short message is required.",
    applyDuplicate: "You already applied to this ad.",
    applyError: "The application could not be sent.",
    myApplications: "My applications",
    applicationsTitle: "Applications",
    applicationsEmpty: "There are no applications yet.",
    downloadCv: "Open CV",
    noCv: "No CV",
    ownerApplications: "Applications for this ad",
    applyPhone: "Phone",
    applyEmail: "Email",
    applyFieldRequired: "Fill in the required fields.",
    applyPhoneInvalid: "The phone number is not valid.",
    applyEmailInvalid: "The email is not valid.",
    applyCvRequired: "The CV must be a PDF, DOC, or DOCX file of up to 5 MB.",
    formTitle: "Application form",
    formLede: "The applicant fills only the fields you select. Each field is required or optional. Up to 5 questions of your own. You can change the form after the ad is published; older applications keep the answers already stored.",
    fieldRequired: "Required",
    formQuestion: "Your question",
    formAddQuestion: "Add a question",
    formRemoveQuestion: "Remove",
    formNeedField: "Select at least one field.",
    formQuestionNeeded: "Write the question.",
    appSubmitted: "submitted",
    appSeen: "seen",
    appRejected: "rejected",
    appWithdraw: "Withdraw application",
    appWithdrawAsk: "Withdraw this application? You can apply again afterwards.",
    appSeenAction: "Mark as seen",
    appRejectAction: "Reject",
    appRejectAsk: "A rejection reason is optional. If you leave it empty, the applicant does not see a reason.",
    appUpdated: "Status updated.",
    appWithdrawn: "Application withdrawn.",
    appStatusError: "The status could not be changed.",
    myApplicationsLede: "Applications you sent on this site. Status: submitted, seen, or rejected.",
    applicationsGate: "Applications need a candidate account.",
    languageAuto: "Automatic",
    profileTitle: "Profile",
    profileLede: "These details stay on the job site. Academy account settings do not open.",
    profileOpen: "Open profile",
    profileCompanyLede: "Company name, city, and a short description. Saving updates this profile.",
    profileApplicantTitle: "Applicant profile",
    profileApplicantLede: "Display name, phone, and email stay on the job site. If an application asks for phone or email and that field is empty, it is filled from here. You can still change it on that application.",
    profileName: "Display name",
    profileNameRequired: "Enter a display name.",
    profileSaved: "Profile saved.",
    profileGate: "The profile is for an employer, applicant, or staff account.",
    notifications: "Notifications",
    notificationsTitle: "Notifications",
    notificationsEmpty: "There are no notifications.",
    notificationsGate: "Sign in to see notifications.",
    notificationsUnread: (n) => `Notifications, ${n} unread`,
    markRead: "Mark as read",
    markAllRead: "Mark all as read",
    noteApplicationNew: (title) => `A new application arrived for «${title}».`,
    noteApplicationSeen: (title) => `Your application for «${title}» was seen.`,
    noteApplicationRejected: (title) => `Your application for «${title}» was rejected.`,
    noteAdApproved: (title) => `Your ad «${title}» was approved.`,
    noteAdRejected: (title) => `Your ad «${title}» was rejected.`,
    noteAdReview: (title) => `Your ad «${title}» is back in review after an edit.`,


  },
  ru: {
    lang: "ru",
    browse: "Смотреть вакансии",
    post: "Разместить вакансию",
    heading: "Открытые вакансии",
    lede: "Ищите по должности или компании. Если город указан, список можно сузить.",
    ecosystemLine: "Часть экосистемы Ingress",
    ecosystemLinkLabel: "Ingress Academy",
    ecosystemFooter: "Ingress Job — площадка вакансий в экосистеме Ingress. Вход через аккаунт Ingress Academy.",
    search: "Поиск",
    searchPlaceholder: "Должность или компания",
    openRole: "Открыть",
    city: "Город",
    allCities: "Все города",
    count: (n) => `${n} ${n % 10 === 1 && n % 100 !== 11 ? "вакансия" : n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 10 || n % 100 >= 20) ? "вакансии" : "вакансий"}`,
    pagePrev: "Назад",
    pageNext: "Дальше",
    pageOf: (page, total) => `Страница ${page} / ${total}`,
    empty: "По этому фильтру вакансий нет.",
    loadError: "Не удалось загрузить вакансии. Проверьте, что API запущен.",
    noCompany: "Компания не указана",
    noCity: "Город не указан",
    source: "Источник",
    back: "К вакансиям",
    breadcrumbs: "Навигация",
    breadcrumbHome: "Вакансии",
    faq: {
      eyebrow: "Вопросы",
      title: "Частые вопросы",
      items: [
        {
          q: "Что такое Ingress Job?",
          a: "Ingress Job — площадка открытых вакансий в Азербайджане и часть экосистемы Ingress. Ищите и фильтруйте по должности, компании, городу, языку и зарплате.",
        },
        {
          q: "Как это связано с Ingress?",
          a: "Ingress Job — продукт семейства Ingress. Вход и регистрация идут через аккаунт Ingress Academy — тот же аккаунт можно использовать в других продуктах экосистемы.",
        },
        {
          q: "Просмотр бесплатный?",
          a: "Да. Открытые вакансии можно читать без аккаунта. Для отклика и размещения нужен аккаунт Ingress Academy.",
        },
        {
          q: "Как искать и фильтровать?",
          a: "Ищите по должности или компании, затем сужайте список по городу, источнику, языку, дате, удалённой работе и диапазону зарплаты.",
        },
        {
          q: "Нужен ли аккаунт для отклика?",
          a: "Да. Зарегистрируйтесь как кандидат — тогда сможете откликаться и следить за откликами.",
        },
        {
          q: "Как разместить вакансию?",
          a: "Зарегистрируйтесь как работодатель, заполните профиль компании и напишите объявление. Перед публикацией оно проходит модерацию.",
        },
        {
          q: "Есть ли удалённые вакансии?",
          a: "Да. Можно отфильтровать удалённые или без города; гибрид и офис тоже есть в списке.",
        },
        {
          q: "Откуда берутся вакансии?",
          a: "В списке могут быть объявления с платформы и открытые вакансии из других источников. У каждой вакансии указан источник.",
        },
        {
          q: "На каких языках можно пользоваться?",
          a: "Сайт доступен на азербайджанском, английском и русском. Язык самой вакансии может отличаться — используйте фильтр языка.",
        },
      ],
    },
    apply: "Откликнуться",
    original: "Оригинал",
    locked: "Нужен аккаунт. Адрес здесь не показывается.",
    missing: "Вакансия не найдена.",
    postTitle: "Кабинет работодателя",
    postBody: "Чтобы написать объявление, зарегистрируйтесь.",
    description: "Описание",
    sources: "Источник",
    companies: "Компания",
    companyPlaceholder: "Название компании",
    inDescription: "Искать и в описании",
    withCity: "Только с городом",
    remote: "Удалённо или без города",
    relocationFilter: "Релокация или визовая поддержка",
    relocationBadge: "Релокация / виза",
    techStack: "Технологии",
    techPlaceholder: "Найти технологию",
    sourceSite: "Сайт источника",
    salaryFilter: "Зарплата",
    salaryMin: "Минимум",
    salaryMax: "Максимум",
    salaryNote: "Включая зарплату по договорённости",
    clear: "Сбросить фильтры",
    filters: "Фильтры",
    sort: "Порядок",
    newest: "Сначала новые",
    oldest: "Сначала старые",
    byTitle: "По названию",
    when: "Дата",
    anyTime: "Все",
    today: "Сегодня",
    week: "Последние 7 дней",
    language: "Язык объявления",
    langAz: "Азербайджанский",
    langEn: "Английский",
        langRu: "Русский",
    register: "Регистрация",
    registerAsk: "С аккаунтом Ingress Academy: публикуете вакансию или откликаетесь?",
    registerPoster: "Публикую вакансию",
    registerCreator: "Откликаюсь",
    signOut: "Выйти",
    roleEmployer: "Работодатель",
    roleCandidate: "Кандидат",
    roleStaff: "Сотрудник",
    companyTitle: "Профиль компании",
    companyLede: "Перед публикацией сохраните название компании, город и короткое описание.",
    companyName: "Название компании",
    companyCity: "Город",
    companyAbout: "Коротко о компании",
    companySave: "Сохранить",
    companyRequired: "Нужны название компании, город и короткое описание.",
    companySaved: "Профиль компании сохранён.",
    ssoError: "Вход не завершился. Попробуйте снова.",
    account: "Аккаунт",
    cabinetLede: "Пишите, правьте и закрывайте свои объявления. Объявление компании не попадает в общий список, пока его не одобрят. После публикации смена заголовка, текста, компании, города или языка снова отправляет его на модерацию.",
    cabinetEmpty: "У вас пока нет объявлений.",
    newAd: "Новое объявление",
    editAd: "Править объявление",
    myAds: "Мои объявления",
    adTitle: "Заголовок",
    adBody: "Текст",
    adSalary: "Зарплата",
    adOptional: "Необязательно",
    adJobType: "Тип работы",
    adJobTypeNone: "Не выбрано",
    jobOffice: "Офис",
    jobHybrid: "Гибрид",
    jobRemoteType: "Удалённо",
    placeRemote: "Удалённо",
    adCityOrRemote: "Город или удалённо",
    adSave: "Сохранить",
    adClose: "Закрыть",
    adCloseAsk: "Закрыть объявление? Оно уйдёт из общего списка.",
    adEdit: "Править",
    adCancel: "Отмена",
    adRequired: "Нужны заголовок, компания, город или удалённо, и текст.",
    adSavedPending: "Объявление отправлено на модерацию.",
    adSavedLive: "Объявление опубликовано.",
    adClosedNote: "Объявление закрыто.",
    statusPending: "На модерации",
    statusPublished: "Опубликовано",
    statusClosed: "Закрыто",
    companyLocked: "Название компании берётся из сохранённого профиля.",
    cannotEdit: "Одобренное объявление уже нельзя править.",
    cabinetError: "Не удалось сохранить объявление.",
    statusRejected: "Отклонено",
    admin: "Модерация",
    adminTitle: "Модерация объявлений",
    adminLede: "Отклоняйте ожидающие объявления с причиной, одобряйте или закрывайте их. Собранные объявления можно править, скрывать и объединять.",
    adminGate: "Модерация доступна только сотрудникам.",
    adminQueue: "Очередь объявлений",
    adminEmpty: "Нет объявлений для модерации.",
    adminApprove: "Одобрить",
    adminReject: "Отклонить",
    adminRejectAsk: "Напишите причину отклонения. Если оставить пустым, объявление не будет отклонено.",
    adminApprovedNote: "Объявление опубликовано.",
    adminRejectedNote: "Объявление отклонено.",
    adminSavedNote: "Изменения сохранены.",
    adminError: "Не удалось выполнить действие.",
    rejectReason: "Причина отклонения",
    rejectReasonRequired: "Нужно написать причину отклонения.",
    resubmitHint: "Сохранение отклонённого объявления снова отправляет его на модерацию и оставляет вне общего списка.",
    reviewHint: "Смена заголовка, текста, компании, города, удалённой работы или языка возвращает объявление на модерацию. Зарплата и тип работы сами по себе остаются опубликованными.",
    cannotChange: "Это объявление уже нельзя изменить.",
    collectedTitle: "Собранные объявления",
    collectedLede: "Отредактируйте автоматически собранное объявление, скройте его с сайта или объедините два дубликата.",
    collectedEmpty: "Собранных объявлений нет.",
    collectedHide: "Скрыть",
    collectedShow: "Показать",
    collectedHidden: "Скрыто",
    collectedKeep: "Оставить это",
    collectedMerge: "Скрыть как дубликат",
    collectedMerged: "Объединено",
    collectedMergeNote: "Дубликат скрыт. Оставленное объявление видно.",
    collectedHideNote: "Объявление скрыто с публичного сайта.",
    collectedShowNote: "Объявление снова в общем списке.",
    collectedKept: "Оставляемое объявление выбрано.",
    manualTitle: "Ссылка на источник вручную",
    manualLede: "Добавьте объявление, которое не собралось автоматически, например из LinkedIn: обязательные поля и исходный адрес. Гость этот адрес не видит.",
    manualUrl: "Исходный адрес",
    manualSaved: "Объявление опубликовано. Адрес открывается только после регистрации.",
    manualUrlInvalid: "Исходный адрес должен быть http или https.",
    applyMessage: "Короткое сообщение",
    applyCv: "CV",
    applyCvHint: "PDF, DOC или DOCX, не больше 5 МБ.",
    applySend: "Отправить отклик",
    applySent: "Отклик отправлен.",
    applyRequired: "Нужно короткое сообщение.",
    applyDuplicate: "Вы уже откликнулись на это объявление.",
    applyError: "Не удалось отправить отклик.",
    myApplications: "Мои отклики",
    applicationsTitle: "Отклики",
    applicationsEmpty: "Откликов пока нет.",
    downloadCv: "Открыть CV",
    noCv: "CV нет",
    ownerApplications: "Отклики на это объявление",
    applyPhone: "Телефон",
    applyEmail: "Эл. почта",
    applyFieldRequired: "Заполните обязательные поля.",
    applyPhoneInvalid: "Номер телефона указан неверно.",
    applyEmailInvalid: "Эл. почта указана неверно.",
    applyCvRequired: "CV должен быть файлом PDF, DOC или DOCX не больше 5 МБ.",
    formTitle: "Форма отклика",
    formLede: "Кандидат заполняет только выбранные поля. Каждое поле обязательное или необязательное. Не больше 5 своих вопросов. Форму можно менять и после публикации; старые отклики хранят уже данные ответы.",
    fieldRequired: "Обязательно",
    formQuestion: "Свой вопрос",
    formAddQuestion: "Добавить вопрос",
    formRemoveQuestion: "Удалить",
    formNeedField: "Выберите хотя бы одно поле.",
    formQuestionNeeded: "Напишите вопрос.",
    appSubmitted: "отправлен",
    appSeen: "просмотрен",
    appRejected: "отклонён",
    appWithdraw: "Отозвать отклик",
    appWithdrawAsk: "Отозвать отклик? После этого можно откликнуться снова.",
    appSeenAction: "Просмотрен",
    appRejectAction: "Отклонить",
    appRejectAsk: "Причина отклонения необязательна. Если оставить пустым, кандидат причину не увидит.",
    appUpdated: "Статус обновлён.",
    appWithdrawn: "Отклик отозван.",
    appStatusError: "Не удалось изменить статус.",
    myApplicationsLede: "Отклики, которые вы отправили на этом сайте. Статус: отправлен, просмотрен или отклонён.",
    applicationsGate: "Отклики доступны аккаунту кандидата.",
    languageAuto: "Автоматически",
    profileTitle: "Профиль",
    profileLede: "Эти данные хранятся на сайте вакансий. Настройки аккаунта Academy не открываются.",
    profileOpen: "Открыть профиль",
    profileCompanyLede: "Название компании, город и короткое описание. Сохранение обновляет этот профиль.",
    profileApplicantTitle: "Профиль кандидата",
    profileApplicantLede: "Имя, телефон и эл. почта остаются на сайте вакансий. Если форма отклика спрашивает телефон или почту, а поле пустое, оно заполняется отсюда. В этом отклике значение всё равно можно изменить.",
    profileName: "Отображаемое имя",
    profileNameRequired: "Напишите отображаемое имя.",
    profileSaved: "Профиль сохранён.",
    profileGate: "Профиль доступен аккаунту работодателя, кандидата или сотрудника.",
    notifications: "Уведомления",
    notificationsTitle: "Уведомления",
    notificationsEmpty: "Уведомлений нет.",
    notificationsGate: "Чтобы видеть уведомления, войдите в аккаунт.",
    notificationsUnread: (n) => `Уведомления, непрочитанных: ${n}`,
    markRead: "Прочитано",
    markAllRead: "Отметить все прочитанными",
    noteApplicationNew: (title) => `По объявлению «${title}» пришёл новый отклик.`,
    noteApplicationSeen: (title) => `Ваш отклик по объявлению «${title}» просмотрен.`,
    noteApplicationRejected: (title) => `Ваш отклик по объявлению «${title}» отклонён.`,
    noteAdApproved: (title) => `Объявление «${title}» одобрено.`,
    noteAdRejected: (title) => `Объявление «${title}» отклонено.`,
    noteAdReview: (title) => `Объявление «${title}» снова на модерации после правки.`,


  },
};

export function text(locale) {
  return copy[locale] || copy.az;
}

export const languageNames = {
  az: { az: "Azərbaycan", en: "İngilis", ru: "Rus", es: "İspan", uk: "Ukrayna", de: "Alman", fr: "Fransız", tr: "Türk", pt: "Portuqal" },
  en: { az: "Azerbaijani", en: "English", ru: "Russian", es: "Spanish", uk: "Ukrainian", de: "German", fr: "French", tr: "Turkish", pt: "Portuguese" },
  ru: { az: "Азербайджанский", en: "Английский", ru: "Русский", es: "Испанский", uk: "Украинский", de: "Немецкий", fr: "Французский", tr: "Турецкий", pt: "Португальский" },
};

export function languageLabel(locale, code) {
  const names = languageNames[locale] || languageNames.az;
  return names[code] || code;
}


export function hrefFor(locale, { mode = "browse", jobId } = {}) {
  const base = locale === "az" ? "" : `/${locale}`;
  if (jobId) return `${base}/jobs/${jobId}`;
  if (mode === "post") return `${base}/post`;
  if (mode === "company") return `${base}/company`;
  if (mode === "admin") return `${base}/admin`;
  if (mode === "applications") return `${base}/applications`;
  if (mode === "profile") return `${base}/profile`;
  if (mode === "notifications") return `${base}/notifications`;
  return base || "/";
}
