function ruPlural(n, one, few, many) {
  const mod10 = n % 10;
  const mod100 = n % 100;
  if (mod10 === 1 && mod100 !== 11) return one;
  if (mod10 >= 2 && mod10 <= 4 && (mod100 < 12 || mod100 > 14)) return few;
  return many;
}

export const copy = {
  az: {
    lang: "az",
    browse: "Elanlara bax",
    post: "Elan yarat",
    ecosystemLine: "Ingress ekosisteminin bir hissəsi",
    ecosystemLinkLabel: "Ingress Academy",
    ecosystemFooter: "Ingress Job — Ingress ekosisteminin iş elanları məhsulu. Giriş Ingress Academy hesabı ilədir.",
    openRole: "Aç",
    allCities: "Bütün şəhərlər",
    count: (n) => `${n} elan`,
    pagePrev: "Əvvəlki",
    pageNext: "Növbəti",
    pageOf: (page, total) => `Səhifə ${page} / ${total}`,
    empty: "Bu süzgəcə uyğun elan yoxdur.",
    loadError: "Elanları yükləmək olmadı. API ünvanı yoxlanılmalıdır.",
    noCompany: "Şirkət göstərilməyib",
    noCity: "Şəhər göstərilməyib",
    source: "Mənbə",
    back: "Elanlara qayıt",
    breadcrumbs: "Yol izi",
    breadcrumbHome: "Elanlar",
    faq: {
      eyebrow: "Suallar",
      title: "Tez-tez verilən suallar",
      items: [
        {
          q: "Ingress Job nədir?",
          a: "Ingress Job Azərbaycanda açıq iş elanlarını bir yerdə göstərən platformadır və Ingress ekosisteminin bir hissəsidir. Vəzifə, şirkət, şəhər, dil və əməkhaqqı üzrə axtarıb süzə bilərsiniz.",
        },
        {
          q: "Ingress ilə əlaqəsi nədir?",
          a: "Ingress Job Ingress layihə ailəsinin məhsuludur. Giriş və qeydiyyat Ingress Academy hesabı ilə gedir — eyni hesab ekosistemdəki digər məhsullarda da istifadə oluna bilər.",
        },
        {
          q: "Elanlara baxmaq pulsuzdur?",
          a: "Bəli. Açıq elanları hesab olmadan da oxuya bilərsiniz. Müraciət və elan yerləşdirmə üçün Ingress Academy hesabı lazımdır.",
        },
        {
          q: "Necə axtarıb filtrləyə bilərəm?",
          a: "Başlıq və ya şirkət üzrə axtarın; şəhər, mənbə, dil, tarix, uzaqdan iş və əməkhaqqı sərhədləri ilə siyahını daraldın.",
        },
        {
          q: "Müraciət etmək üçün hesab lazımdır?",
          a: "Bəli. Namizəd kimi qeydiyyatdan keçəndən sonra elana müraciət edə və müraciətlərinizi izləyə bilərsiniz.",
        },
        {
          q: "İş elanı necə yerləşdirilir?",
          a: "İşəgötürən kimi qeydiyyatdan keçin, şirkət profilini doldurun və elanı yazın. Dərcdən əvvəl elan moderasiyadan keçir.",
        },
        {
          q: "Uzaqdan iş elanları varmı?",
          a: "Bəli. Uzaqdan və ya şəhəri göstərilməyən elanları filtrlə seçə bilərsiniz; hibrid və ofis elanları da siyahıdadır.",
        },
        {
          q: "Elanlar haradan gəlir?",
          a: "Siyahıda həm platformada yazılmış elanlar, həm də toplanmış açıq mənbə elanları ola bilər. Hər elanda mənbə göstərilir.",
        },
        {
          q: "Hansı dillərdə istifadə edə bilərəm?",
          a: "Sayt Azərbaycan, İngilis və Rus dillərindədir. Elanın öz dili fərqli ola bilər — dil filtrindən istifadə edin.",
        },
      ],
    },
    apply: "Müraciət et",
    original: "Orijinal elan",
    locked: "Hesab tələb olunur. Ünvan burada göstərilmir.",
    missing: "Elan tapılmadı.",
    postTitle: "İşəgötürən kabineti",
    postBody: "Elan yazmaq üçün qeydiyyatdan keçin.",
    postCandidateTitle: "Elan yerləşdirmək şirkət hesabları üçündür",
    postCandidateBody: "Siz namizəd hesabı ilə daxil olmusunuz. İş elanını işəgötürən (şirkət) hesabları və Ingress əməkdaşları yerləşdirə bilər.",
    postBecomeEmployer: "Şirkət hesabı ilə davam et",
    postBackToJobs: "Elanlara qayıt",
    description: "Təsvir",
    sources: "Mənbə",
    companies: "Şirkət",
    companyPlaceholder: "Şirkət adı",
    remoteFilter: "Uzaqdan iş",
    relocationFilter: "Relokasiya və ya viza dəstəyi",
    relocationBadge: "Relokasiya / viza",
    techStack: "Texnologiyalar",
    techPlaceholder: "Texnologiya axtarın",
    categoryFilter: "Kateqoriya",
    sourceSite: "Mənbə saytı",
    navCompanies: "Şirkətlər",
    navTrends: "Trendlər",
    trendsTitle: "Bacarıq trendləri",
    trendsLede: "İzlədiyimiz elanlarda bacarıq tələbinin payı və həftəlik dəyişimi.",
    trendsEmpty: "Hələ trend məlumatı yoxdur. Worker gündəlik aqreqat toplayanda görünəcək.",
    trendsShare: "Pay",
    trendsGrowth: "Həftəlik artım",
    trendsAds: "Elan",
    trendsAdsCount: (n) => `${n} elan`,
    trendsSalaryLabel: "Median maaş",
    trendsSalary: (median, currency) => `Median maaş: ${median} ${currency}/il`,
    trendsSalaryMedian: (median, currency) => `${median} ${currency}/il`,
    trendsSalaryRange: (low, high, currency) => `${low}–${high} ${currency}`,
    trendsSalaryN: (n) => `${n} elan əsasında`,
    trendsOftenWith: "Tez-tez birlikdə",
    trendsOftenWithItem: (name, pct) => `${name} (${pct}%)`,
    trendsAsOf: (day) => `Tarix: ${day}`,
    trendsAsOfLabel: "Tarix",
    trendsWindow: (n) => `Son ${n} gün`,
    trendsWindowLabel: "Dövr",
    trendsWindowPrefix: "Son",
    trendsWindowUnit: "gün",
    trendsWindowApply: "Göstər",
    trendsDisclaimer: "Trendlər yalnız Ingress Job-un izlədiyi elanlar əsasında hesablanır, bütün bazarı əks etdirmir.",
    trendsDetailKicker: "Bacarıq trendi",
    trendsDetailBack: "Trendlərə qayıt",
    trendsDetailJobs: "Bu bacarığı tələb edən elanlar",
    trendsDetailJobsBack: "Trendə qayıt",
    trendsDetailJobsEmpty: "Bu bacarıq üçün açıq elan tapılmadı.",
    trendsDetailYou: "Siz və bu trend",
    trendsDetailHaveFocus: "Bu bacarıq profilinizdə var.",
    trendsDetailMissingFocus: "Bu bacarıq hələ profilinizdə yoxdur.",
    trendsDetailCompanionsHave: "Birlikdə tələb olunanlardan sizdə var",
    trendsDetailCompanionsLearn: "Ora çatmaq üçün öyrənin",
    trendsDetailGuest: "Profilinizlə müqayisə üçün namizəd kimi daxil olun.",
    trendsDetailGuestCta: "Daxil ol / qeydiyyat",
    trendsDetailNotFound: "Bu bacarıq üçün trend tapılmadı.",
    companiesTitle: "Şirkətlər",
    companiesLede: "Şirkətlər üzrə elanlar, texnologiyalar və müraciətlər",
    companiesSearch: "Şirkət axtar",
    companiesSearchButton: "Axtar",
    sortMostJobs: "Ən çox elan",
    sortAZ: "A–Z",
    sortMostApplications: "Ən çox müraciət",
    companiesEmpty: "Bu axtarışa uyğun şirkət tapılmadı.",
    companiesEmptyAll: "Hələ açıq elanı olan şirkət yoxdur.",
    companiesReset: "Bütün şirkətlər",
    companiesLoading: "Şirkətlər yüklənir…",
    openJobs: (n) => `${n} açıq elan`,
    statOpenJobs: "Açıq elan",
    statApplications: "Müraciət",
    statPerJob: "Elan başına",
    statPopularity: "Populyarlıq",
    popularityHelp: "Populyarlıq: platformadakı açıq elanlara bu sayt vasitəsilə göndərilən bütün müraciətlərdən bu şirkətin payı.",
    statLocations: "Yerlər",
    statRemoteShare: "Uzaqdan iş payı",
    remoteJobs: (n) => `${n} uzaqdan`,
    relocationJobs: (n) => `${n} relokasiya`,
    companyJobs: "Şirkətin açıq elanları",
    companyCategories: "Kateqoriyalar",
    latestPosted: "Son elan",
    applicationsCount: (n) => `${n} müraciət`,
    applicationsNone: "Hələ müraciət yoxdur, ilk sən ol",
    applicationsFirst: "İlk müraciət edən ol",
    applicationsNote: "Yalnız bu sayt vasitəsilə göndərilən müraciətlər sayılır.",
    keyFacts: "Əsas məlumatlar",
    factLocation: "Yer",
    factPosted: "Dərc tarixi",
    salaryFilter: "Əməkhaqqı",
    salaryMin: "Minimum",
    salaryMax: "Maksimum",
    salaryNote: "Razılaşma ilə olanlar da daxildir",
    clear: "Filtrləri təmizlə",
    filters: "Filtrlər",
    filtersApply: "Tətbiq et",
    filtersClear: "Təmizlə",
    filtersClose: "Filtrləri bağla",
    filtersActive: (n) => `${n} aktiv filtr`,
    menuOpen: "Menyunu aç",
    menuClose: "Menyunu bağla",
    menuLabel: "Menyu",
    sort: "Sıra",
    newest: "Ən yeni",
    oldest: "Ən köhnə",
    byTitle: "Başlığa görə",
    when: "Tarix",
    anyTime: "Hamısı",
    today: "Bu gün",
    week: "Son 7 gün",
    language: "Elanın dili",
    langAz: "Azərbaycan",
    langEn: "İngilis",
        langRu: "Rus",
    register: "Qeydiyyat",
    registerAsk: "Ingress Academy hesabı ilə: elan paylaşan, yoxsa müraciət edən?",
    registerEmployerUpgrade: "İşəgötürən kimi də elan yerləşdirmək istəyirsiniz?",
    registerPoster: "Elan paylaşan",
    registerCreator: "Müraciət edən",
    signOut: "Çıxış",
    roleEmployer: "İşəgötürən",
    roleCandidate: "Namizəd",
    roleStaff: "Əməkdaş",
    companyTitle: "Şirkət profili",
    companyLede: "Elan yerləşdirməzdən əvvəl şirkət adı, şəhər və qısa təsvir saxlanmalıdır. Sonra dəyişiklikləri Profil səhifəsindən edin.",
    companyName: "Şirkət adı",
    companyCity: "Şəhər",
    companyAbout: "Qısa təsvir",
    companySave: "Saxla",
    companyRequired: "Şirkət adı, şəhər və qısa təsvir doldurulmalıdır.",
    companySaved: "Şirkət profili saxlanıldı.",
    companyEditOnProfile: "Şirkət profili artıq tamamdır. Dəyişiklikləri Profil səhifəsindən edin.",
    companyGoProfile: "Profilə keç",
    ssoError: "Giriş alınmadı. Yenidən cəhd edin.",
    account: "Hesab",
    accountSignedIn: "Daxil olub",
    cabinetLede: "Öz elanlarınızı yazın, redaktə edin və bağlayın. Şirkət elanı təsdiqə qədər ictimai siyahıda görünmür. Dərcdən sonra başlıq, mətn, şirkət, şəhər və ya dil dəyişəndə elan yenidən moderasiyaya düşür.",
    cabinetEmpty: "Hələ elanınız yoxdur.",
    newAd: "Yeni elan",
    editAd: "Elanı redaktə et",
    myAds: "Elanlarım",
    cabinetApplicationsTab: "Müraciətlər",
    ownerApplicationsAll: "Bütün müraciətlər",
    adTitle: "Başlıq",
    adBody: "Mətn",
    adSalary: "Əməkhaqqı",
    adOptional: "İstəyə bağlı",
    adJobType: "İş növü",
    adJobTypeNone: "Seçilməyib",
    jobOffice: "Ofis",
    jobHybrid: "Hibrid",
    jobRemoteType: "Uzaqdan",
    placeRemote: "Uzaqdan",
    adCityOrRemote: "Şəhər və ya uzaqdan",
    adSave: "Saxla",
    adClose: "Bağla",
    adCloseAsk: "Elan bağlansın? İctimai siyahıdan çıxacaq.",
    adEdit: "Redaktə",
    adCancel: "Ləğv et",
    adRequired: "Başlıq, şirkət, şəhər və ya uzaqdan, və mətn doldurulmalıdır.",
    adSavedPending: "Elan moderasiyaya göndərildi.",
    adSavedLive: "Elan dərc olundu.",
    adClosedNote: "Elan bağlandı.",
    statusPending: "Moderasiyada",
    statusPublished: "Dərc olunub",
    statusClosed: "Bağlanıb",
    companyLocked: "Şirkət adı saxlanmış profildən gəlir.",
    cannotEdit: "Təsdiqlənmiş elan dəyişdirilə bilməz.",
    cabinetError: "Elanı saxlamaq olmadı.",
    statusRejected: "Rədd edilib",
    admin: "Moderasiya",
    adminTitle: "Elan moderasiyası",
    adminLede: "Gözləyən elanları səbəblə rədd edin, təsdiqləyin və ya bağlayın. Toplanmış elanları redaktə edin, gizlədin və ya birləşdirin.",
    adminGate: "Moderasiya yalnız əməkdaş hesabı üçündür.",
    adminQueue: "Elan növbəsi",
    adminEmpty: "Moderasiya üçün elan yoxdur.",
    adminApprove: "Təsdiqlə",
    adminReject: "Rədd et",
    adminRejectAsk: "Rədd səbəbini yazın. Boş saxlasanız, elan rədd edilməyəcək.",
    adminApprovedNote: "Elan dərc olundu.",
    adminRejectedNote: "Elan rədd edildi.",
    adminSavedNote: "Dəyişikliklər saxlanıldı.",
    adminError: "Əməliyyat alınmadı.",
    rejectReason: "Rədd səbəbi",
    rejectReasonRequired: "Rədd səbəbi yazılmalıdır.",
    resubmitHint: "Rədd edilmiş elanı saxlayanda o yenidən moderasiyaya düşür və ictimai siyahıdan kənarda qalır.",
    reviewHint: "Başlıq, mətn, şirkət, şəhər, uzaqdan və ya dil dəyişəndə elan yenidən moderasiyaya düşür. Yalnız əməkhaqqı və iş növü dərcdə qalır.",
    cannotChange: "Bu elan dəyişdirilə bilməz.",
    collectedTitle: "Toplanmış elanlar",
    collectedLede: "Avtomatik toplanmış elanı redaktə edin, ictimai saytdan gizlədin və ya iki dublikatı birləşdirin.",
    collectedEmpty: "Toplanmış elan yoxdur.",
    collectedHide: "Gizlət",
    collectedShow: "Göstər",
    collectedHidden: "Gizlədilib",
    collectedKeep: "Saxlanılan budur",
    collectedMerge: "Dublikatı gizlət",
    collectedMerged: "Birləşdirilib",
    collectedMergeNote: "Dublikat gizlədildi. Saxlanılan elan görünür.",
    collectedHideNote: "Elan ictimai saytdan gizlədildi.",
    collectedShowNote: "Elan yenidən ictimai siyahıdadır.",
    collectedKept: "Saxlanılan elan seçildi.",
    manualTitle: "Əl ilə mənbə keçidi",
    manualLede: "Avtomatik toplanmayan elanı, məsələn LinkedIn, məcburi sahələr və orijinal ünvanla əlavə edin. Qonaq ünvanı görmür.",
    manualUrl: "Orijinal ünvan",
    manualSaved: "Elan dərc olundu. Ünvan yalnız qeydiyyatdan sonra açılır.",
    manualUrlInvalid: "Orijinal ünvan http və ya https olmalıdır.",
    applyMessage: "Qısa müraciət",
    applyCv: "CV",
    applyCvHint: "PDF, DOC və ya DOCX, ən çox 5 MB.",
    applySend: "Müraciəti göndər",
    applySent: "Müraciət göndərildi.",
    applyRequired: "Qısa müraciət yazılmalıdır.",
    applyDuplicate: "Bu elana artıq müraciət etmisiniz.",
    applyError: "Müraciət göndərilmədi.",
    myApplications: "Müraciətlərim",
    savedJobs: "Saxlanmış elanlar",
    savedJobsLede: "Sonra baxmaq üçün saxladığınız elanlar.",
    savedJobsEmpty: "Hələ saxlanmış elan yoxdur.",
    savedJobsGate: "Saxlanmış elanlar hesab tələb edir.",
    saveJob: "Elanı saxla",
    unsaveJob: "Saxlanandan çıxar",
    saveJobError: "Elanı saxlamaq olmadı.",
    talentTitle: "Namizəd axtarışı",
    talentLede: "Razılıq vermiş namizədlərin CV profilinə baxın. Əlaqə sorğusu hələ yoxdur.",
    talentSearch: "Axtar",
    talentSearchLabel: "Axtarış",
    talentSearchPlaceholder: "Başlıq, bacarıq və ya səviyyə",
    talentEmpty: "Uyğun namizəd tapılmadı.",
    talentGateGuest: "Namizəd axtarışı işəgötürən hesabı tələb edir.",
    talentGateRole: "Bu səhifə yalnız işəgötürən və əməkdaş hesabları üçündür.",
    talentGateCompany: "Əvvəl şirkət profilini tamamlayın.",
    talentAnonymous: "Anonim namizəd",
    talentVisibilityAnonymous: "Anonim",
    talentVisibilityPublic: "Açıq profil",
    talentYears: (n) => `${n} il təcrübə`,
    applicationsTitle: "Müraciətlər",
    adminAiTitle: "AI axınları",
    adminAiLede: "Hər axını ayrıca yandırın və ya söndürün. Dəyişən silməyə ehtiyac yoxdur; açar qalır, çağırış dayandırılır.",
    adminAiNoKey: "OPENAI_API_KEY qoyulmayıb. Toggle-lar saxlanır, amma model çağırışı getmir.",
    adminAiGateway: "Ümumi AI gateway (LLM və embed)",
    adminAiCv: "CV parse ehtiyatı (AI #1)",
    adminAiTidy: "Elan mətnini təmizləmə",
    adminAiEmbeddings: "Vakansiya və profil embed-ləri",
    adminAiRerank: "Uyğunluq rerank (AI #2)",
    adminAiLlmRerank: "LLM uyğunluq re-rank (top-10)",
    adminAiWhy: "Uyğunluq «niyə» cümləsi",
    adminAiRoleCoach: "Rol bacarıq koçu",
    adminAiDigest: "Digest giriş mətni (AI #4)",
    adminAiEngagement: "Engagement bildiriş mətni",
    adminAiSaved: "AI ayarları saxlanıldı.",
    applicationsEmpty: "Hələ müraciət yoxdur.",
    downloadCv: "CV-ni aç",
    noCv: "CV yoxdur",
    ownerApplications: "Bu elana müraciətlər",
    applyPhone: "Telefon",
    applyEmail: "E-poçt",
    applyFieldRequired: "Məcburi sahələr doldurulmalıdır.",
    applyPhoneInvalid: "Telefon nömrəsi düzgün deyil.",
    applyEmailInvalid: "E-poçt düzgün deyil.",
    applyCvRequired: "CV faylı PDF, DOC və ya DOCX olmalıdır və 5 MB-dan böyük ola bilməz.",
    formTitle: "Müraciət forması",
    formLede: "Namizəd yalnız seçilmiş sahələri doldurur. Hər sahə məcburi və ya istəyə bağlı ola bilər. Ən çox 5 öz sualı. Formanı dərcdən sonra da dəyişmək olar; köhnə müraciətlər öz cavabını saxlayır.",
    fieldRequired: "Məcburi",
    formQuestion: "Öz sualı",
    formAddQuestion: "Sual əlavə et",
    formRemoveQuestion: "Sil",
    formNeedField: "Ən azı bir sahə seçilməlidir.",
    formQuestionNeeded: "Sual yazılmalıdır.",
    appSubmitted: "göndərildi",
    appSeen: "baxıldı",
    appRejected: "rədd edildi",
    appWithdraw: "Geri götür",
    appWithdrawAsk: "Müraciət geri götürülsün? Sonra yenidən müraciət etmək olar.",
    appSeenAction: "Baxıldı",
    appRejectAction: "Rədd et",
    appRejectAsk: "Rədd səbəbi istəyə bağlıdır. Boş saxlasanız, namizəd səbəb görməyəcək.",
    appUpdated: "Status yeniləndi.",
    appWithdrawn: "Müraciət geri götürüldü.",
    appStatusError: "Statusu dəyişmək olmadı.",
    appTimelineLabel: "Status tarixçəsi",
    appEmployerNote: "Qeyd: ",
    myApplicationsLede: "Göndərdiyiniz müraciətlərin statusu və işəgötürən qeydləri.",
    applicationsGate: "Müraciətlər namizəd hesabı tələb edir.",
    languageAuto: "Avtomatik",
    profileTitle: "Profil",
    profileLede: "Bu məlumatlar job saytında saxlanır. Academy hesab ayarları açılmır.",
    profileOpen: "Profili aç",
    profileCompanyLede: "Şirkət adı, şəhər və qısa təsvir. Saxlayanda profil yenilənir.",
    profileApplicantTitle: "Namizəd profili",
    profileApplicantLede: "Görünən ad, telefon və e-poçt job saytında qalır. Müraciət forması telefon və ya e-poçt istəsə və sahə boşdursa, buradan doldurulur. Həmin müraciətdə dəyişmək olar.",
    profileCvCtaLede: "Bacarıq, təcrübə və tövsiyələr üçün tam CV profilini doldurun.",
    profileName: "Görünən ad",
    profileNameRequired: "Görünən ad yazılmalıdır.",
    profileSaved: "Profil saxlanıldı.",
    privacyTitle: "Məxfilik və razılıqlar",
    privacyLede: "CV təhlili, e-poçt və recruiter görünməsi üçün ayrı seçimlər. Hamısı standart olaraq sönülüdür.",
    privacySaved: "Razılıqlar saxlanıldı.",
    privacyError: "Razılıqları saxlamaq olmadı.",
    privacyExportError: "Məlumatları yükləmək olmadı.",
    privacyDeleteConfirm: "Bütün namizəd məlumatlarınız (profil, CV, razılıqlar) silinəcək. Davam?",
    privacyDeleteDone: "Məlumatlarınız silindi.",
    privacyDeleteError: "Məlumatları silmək olmadı.",
    privacyWhoViewedSoon: "Bu funksiya tezliklə əlavə olunacaq.",
    profileGate: "Profil işəgötürən, namizəd və ya əməkdaş hesabı üçündür.",
    profileReviewTitle: "CV profilini yoxla",
    profileReviewLede: "CV yükləyin — sahələr avtomatik dolsun — və ya özünüz doldurun. Hər sahəni redaktə edə bilərsiniz.",
    profileReviewOpen: "CV profilini yoxla",
    profileReviewEmpty: "Hələ profil yoxdur. CV yükləyin və ya əl ilə doldurun.",
    profileReviewPending: "Hazır olanda sahələr avtomatik dolacaq.",
    profileReviewFailed: "Son CV təhlili alınmadı. Yenidən yükləyə və ya əl ilə doldura bilərsiniz.",
    profileReviewCancelParse: "Ləğv et",
    profileReviewCancelDone: "CV təhlili ləğv edildi. Yenidən yükləyə və ya əl ilə doldura bilərsiniz.",
    profileReviewStalled: "Təhlil çox uzun çəkdi. Ləğv edib yenidən yükləyə və ya əl ilə doldura bilərsiniz.",
    profileReviewChooserTitle: "Profili necə dolduraq?",
    profileReviewChooserLede: "CV-dən çıxarılan məlumatı yoxlayıb düzəldə bilərsiniz.",
    profileReviewOptionUpload: "CV yüklə",
    profileReviewOptionUploadHint: "PDF, DOC və ya DOCX — sistem məlumatı çıxaracaq.",
    profileReviewOptionManual: "Əl ilə doldur",
    profileReviewOptionManualHint: "Boş forma açılır; istədiyiniz kimi yazın.",
    profileReviewUploadTitle: "CV mənbəyi",
    profileReviewUploadHint: "PDF, DOC və ya DOCX, ən çox 5 MB. Yükləyəndən sonra formu redaktə edə bilərsiniz.",
    profileReviewUploadCta: "CV seç",
    profileReviewReuploadCta: "CV yenilə",
    profileReviewUploading: "Yüklənir…",
    profileReviewUploadQueued: "CV qəbul olundu. Təhlil gedir…",
    profileReviewUploadError: "CV yükləmək olmadı.",
    profileReviewUploadedName: (name) => `Son yüklənən: ${name}`,
    profileReviewFilledFromCv: "CV-dən məlumat dolduruldu. Lazım gələrsə düzəldin və təsdiqləyin.",
    profileReviewManualBadge: "Əl ilə doldurulur",
    profileReviewProgressTitle: "CV təhlil olunur",
    profileReviewStepUpload: "Yükləmə",
    profileReviewStepQueue: "Növbə",
    profileReviewStepParse: "Təhlil",
    profileReviewBasics: "Əsas məlumat",
    profileReviewTabBasics: "Əsas",
    profileReviewTabExperience: "Təcrübə",
    profileReviewTabMore: "Təhsil və dillər",
    profileReviewCheck: "CV-dən zəif oxundu — yoxlayın",
    profileReviewHeadline: "Başlıq",
    profileReviewAbout: "Haqqında",
    profileReviewAboutHint: "Qısa özünüzü təqdim edin — təcrübə, istiqamət, məqsəd.",
    profileReviewSeniority: "Səviyyə",
    profileReviewYears: "Ümumi təcrübə (il)",
    profileReviewSkills: "Bacarıqlar",
    profileReviewSkillsEmpty: "Hələ bacarıq yoxdur.",
    profileReviewSkillAdd: "Əlavə et",
    profileReviewSkillName: "Bacarıq",
    profileReviewSkillYears: "il",
    profileReviewSkillEdit: "Redaktə üçün toxunun",
    profileReviewWork: "İş təcrübəsi",
    profileReviewWorkEmpty: "Hələ iş təcrübəsi yoxdur.",
    profileReviewWorkAdd: "İş əlavə et",
    profileReviewWorkItem: (n) => `İş #${n}`,
    profileReviewRemove: "Sil",
    profileReviewJobTitle: "Vəzifə",
    profileReviewCompany: "Şirkət",
    profileReviewLocation: "Lokasiya",
    profileReviewJobSummary: "Təsvir",
    profileReviewStart: "Başlanğıc",
    profileReviewEnd: "Son",
    profileReviewPresent: "indi",
    profileReviewEducation: "Təhsil",
    profileReviewEducationEmpty: "Hələ təhsil yoxdur.",
    profileReviewEducationAdd: "Təhsil əlavə et",
    profileReviewEducationItem: (n) => `Təhsil #${n}`,
    profileReviewDegree: "Dərəcə",
    profileReviewField: "İxtisas",
    profileReviewSchool: "Məktəb / Universitet",
    profileReviewEduYear: "İl",
    profileReviewLanguages: "Dillər",
    profileReviewLanguagesEmpty: "Hələ dil yoxdur.",
    profileReviewLanguageAdd: "Dil əlavə et",
    profileReviewLangCode: "Dil",
    profileReviewLangLevel: "Səviyyə",
    profileReviewLangNative: "Ana dil",
    profileReviewLangLabel: (code) =>
      ({ az: "Azərbaycan", en: "İngilis", ru: "Rus", tr: "Türk", de: "Alman", fr: "Fransız" }[code] || code),
    profileReviewLinks: "Linklər",
    profileReviewLinkedin: "LinkedIn",
    profileReviewGithub: "GitHub",
    profileReviewPortfolio: "Portfolio / sayt",
    profileReviewContact: "Əlaqə",
    profileReviewFullName: "Ad",
    profileReviewCity: "Şəhər",
    profileReviewCountry: "Ölkə",
    profileReviewStatusDraft: "Qaralama",
    profileReviewStatusConfirmed: "Təsdiqlənib",
    profileReviewConfidence: (n) => `Güvən: ${Math.round(n * 100)}%`,
    profileReviewSave: "Saxla",
    profileReviewConfirm: "Profili təsdiqlə",
    profileReviewReset: "Sıfırla",
    profileReviewResetConfirm: "Profil tamamilə silinəcək. Yenidən CV yükləyə və ya əl ilə doldura bilərsiniz. Davam edək?",
    profileReviewResetDone: "Profil sıfırlandı.",
    profileReviewResetError: "Profili sıfırlamaq olmadı.",
    profileReviewSaved: "Profil saxlanıldı.",
    profileReviewConfirmed: "Profil təsdiqləndi.",
    profileReviewError: "Profili saxlamaq olmadı.",
    profileReviewRolesTitle: "Uyğun rollar",
    profileReviewRolesEmpty: "Hələ rol təklifi yoxdur. Bacarıqları əlavə edib saxlayın.",
    profileReviewRolesConsent: "Rol təklifləri üçün CV təhlili / matching razılığını aktiv edin.",
    profileReviewRolesConsentLink: "Məxfilik ayarları",
    profileReviewRolesScore: (n) => `${Math.round(n * 100)}%`,
    recommendationsOpen: "Tövsiyələr",
    recommendationsTitle: "Tövsiyələr",
    recommendationsLede: "Rol seçin — öyrənmək üçün, sizdə var və uyğun elanlar.",
    recommendationsDisclaimer: "Skor qayda əsaslıdır; mövcud olduqda AI yenidən sıralama və izah əlavə oluna bilər.",
    recommendationsGate: "Tövsiyələr namizəd hesabı tələb edir.",
    recommendationsConsent: "Tövsiyələr üçün CV təhlili / matching razılığını aktiv edin.",
    recommendationsConsentLink: "Məxfilik ayarları",
    recommendationsRoles: "Uyğun rollar",
    recommendationsSelectedRole: "Seçilmiş rol",
    recommendationsJobs: "Uyğun elanlar",
    recommendationsEmptyRoles: "Hələ rol təklifi yoxdur. Bacarıqları profilə əlavə edin.",
    recommendationsEmptyJobs: "Hələ uyğun elan yoxdur. Profili tamamlayın və ya bir az sonra yeniləyin.",
    recommendationsScore: (n) => `${Math.round(n * 100)}%`,
    recommendationsUp: "Uyğundur",
    recommendationsDown: "Uyğun deyil",
    recommendationsReason: "Səbəb",
    recommendationsReasonLocation: "Lokasiya",
    recommendationsReasonSeniority: "Səviyyə",
    recommendationsReasonTechnology: "Texnologiya",
    recommendationsReasonSalary: "Maaş",
    recommendationsGap: "Bacarıq boşluğu",
    recommendationsGapEmpty: "Bu rol üçün boşluq hesablanmadı.",
    recommendationsGapLearn: "Öyrənmək üçün",
    recommendationsGapShare: (pct) => `${pct}% pay`,
    recommendationsGapGrowth: (pct) => `${pct > 0 ? "+" : ""}${pct}% həftəlik`,
    recommendationsGapGrowthSurge: "Kəskin artım",
    recommendationsGapGrowthDrop: "Kəskin azalma",
    recommendationsGapOftenWith: (base, pct) => `${base} elanlarının ~${pct}%-də tələb olunur`,
    recommendationsFeedbackSaved: "Rəy saxlanıldı.",
    recommendationsFeedbackError: "Rəyi saxlamaq olmadı.",
    recommendationsGapCourse: "Academy kursu",
    recommendationsGapCareerPath: "Academy karyera yolu",
    recommendationsGapLink: "Bacarıq boşluğu və Academy kursları",
    skillsOpen: "Bacarıqlar",
    skillsTitle: "Bacarıqlar və boşluq",
    skillsLede: "Rol seçin — nəyi bilirsiniz, nəyi öyrənməlisiniz və Academy kursları.",
    skillsGate: "Bacarıq analizi namizəd hesabı tələb edir.",
    skillsTargetRole: "Hədəf rol",
    skillsHave: "Sizdə var",
    skillsMissing: "Çatışmır",
    skillsHaveCount: (n) => `${n} var`,
    skillsMissingCount: (n) => `${n} çatışmır`,
    skillsHaveEmpty: "Bu rol üçün təsdiqlənmiş bacarıq yoxdur.",
    skillsMissingEmpty: "Bu rol üçün çatışmayan bacarıq yoxdur.",
    skillsCoachTitle: "Rol koçu",
    skillsCoachMustLearn: "Əvvəl öyrənin",
    skillsCoachStrong: "Güclü tərəflər",
    skillsCoachTransferable: "Keçid bacarıqları",
    skillsCoachTransfer: (from, to) => `${from} → ${to}`,
    recommendationsCoachMore: "Tam koç məsləhəti",
    insightsOpen: "İnsights",
    insightsTitle: "Bu həftənin insights",
    insightsLede: "Öyrənmə planı, yaxın elanlar və Academy tövsiyələri — bir yerdə.",
    insightsGate: "İnsights namizəd hesabı tələb edir.",
    insightsCoachTitle: "Həftəlik öyrənmə planı",
    insightsCoachRole: (role) => `Rol: ${role}`,
    insightsCoachEmpty: "Hələ koç planı yoxdur. Profili təsdiqləyin və matching razılığını aktiv edin.",
    insightsNearTitle: "Yaxın elanlar",
    insightsNearEmpty: "Hələ yaxın elan yoxdur.",
    insightsGrowthTitle: "Öyrənmə yolu",
    insightsGrowthEmpty: "Hələ Academy və ya roadmap tövsiyəsi yoxdur.",
    noticeCtaOpen: "Bax",
    noticeCtaLearn: "Öyrən",
    noticeCtaInsights: "İnsights",
    noticeCtaProfile: "Profili tamamla",
    noticeRoadmapTitle: "Öyrənmə addımları",
    noticeComingSoon: "Ingress training tezliklə",
    emailSettingsOpen: "Bildiriş seçimləri",
    emailSettingsTitle: "Bildiriş seçimləri",
    emailSettingsLede: "E-poçt dayjesti, uyğunluq xəbərdarlıqları və push. Tranzaksion məktublar ayrıca qalır.",
    emailSettingsGate: "Bildiriş seçimləri namizəd hesabı tələb edir.",
    emailSettingsPrivacyLink: "Məxfilik və razılıqlar",
    emailSettingsConsentOff: "Marketinq e-poçtları üçün razılıq söndürülüb.",
    emailSettingsFrequency: "Tezlik",
    emailSettingsLanguage: "E-poçt dili",
    emailSettingsWeekday: "Göndərmə günü",
    emailSettingsDigest: "Həftəlik / iki həftəlik dayjest",
    emailSettingsHighMatch: "Yüksək uyğunluq xəbərdarlığı",
    emailSettingsMatchNear: "Yaxın elanlar (skill artımı tövsiyəsi)",
    emailSettingsProfileNudge: "Profil tamamlama xatırlatması",
    emailSettingsCoachWeekly: "Həftəlik öyrənmə planı",
    emailSettingsPush: "Brauzer push bildirişləri (master)",
    emailSettingsPushEnable: "Bildiriş icazəsi ver",
    emailSettingsPushDisable: "Push abunəliyini sil",
    emailSettingsPushHint:
      "Brauzer icazəsi və abunəlik lazımdır. iOS-da yalnız ana ekrana əlavə edilmiş PWA və HTTPS.",
    emailSettingsPushOn: "Brauzer push aktivdir.",
    emailSettingsPushDenied: "Brauzer bildiriş icazəsi rədd edildi. Parametrlərdən aça bilərsiniz.",
    emailSettingsPushUnsupported: "Bu brauzer Web Push dəstəkləmir.",
    emailSettingsPushVapid: "Push server konfiqurasiya olunmayıb (VAPID).",
    emailSettingsPushError: "Push abunəliyi alınmadı.",
    emailSettingsSaved: "Bildiriş seçimləri saxlanıldı.",
    emailSettingsError: "Seçimləri saxlamaq olmadı.",
    emailFreqWeekly: "Həftəlik",
    emailFreqBiweekly: "İki həftəlik",
    emailFreqImportant: "Yalnız vacib",
    emailFreqNone: "Heç biri",
    emailWeekdayMon: "Bazar ertəsi",
    emailWeekdayTue: "Çərşənbə axşamı",
    emailWeekdayWed: "Çərşənbə",
    emailWeekdayThu: "Cümə axşamı",
    emailWeekdayFri: "Cümə",
    emailWeekdaySat: "Şənbə",
    emailWeekdaySun: "Bazar",
    unsubscribeTitle: "Abunəlikdən çıxış",
    unsubscribeLede: "Marketinq və tövsiyə e-poçtlarını dayandırmaq istəyirsiniz?",
    unsubscribeConfirm: "Abunəlikdən çıx",
    unsubscribeManage: "E-poçt seçimlərinə keç",
    unsubscribeDone: "Abunəlik dayandırıldı. Tranzaksion məktublar (məs. müraciət statusu) göndərilə bilər.",
    unsubscribeInvalid: "Link etibarsızdır və ya vaxtı keçib.",
    unsubscribeLoading: "Yoxlanılır…",
    notifications: "Bildirişlər",
    notificationsTitle: "Bildirişlər",
    notificationsEmpty: "Bildiriş yoxdur.",
    notificationsGate: "Bildirişlər üçün hesaba daxil olun.",
    notificationsUnread: (n) => `Bildirişlər, ${n} oxunmamış`,
    markRead: "Oxundu",
    markAllRead: "Hamısını oxunmuş et",
    noteApplicationNew: (title) => `«${title}» elanına yeni müraciət gəldi.`,
    noteApplicationSeen: (title) => `«${title}» elanına müraciətinizə baxıldı.`,
    noteApplicationRejected: (title) => `«${title}» elanına müraciətiniz rədd edildi.`,
    noteAdApproved: (title) => `«${title}» elanınız təsdiqləndi.`,
    noteAdRejected: (title) => `«${title}» elanınız rədd edildi.`,
    noteAdReview: (title) => `«${title}» elanınız dəyişiklikdən sonra yenidən moderasiyadadır.`,
    noteMatchNew: (title) => `Sənə uyğun yeni elan: «${title}».`,
    noteMatchNear: (title) => `Yaxın elan — skill artır: «${title}».`,
    noteProfileNudge: () => "Profilini tamamla — uyğun elanlar üçün CV və skill-lər lazımdır.",
    noteCoachWeekly: () => "Bu həftənin öyrənmə planı hazırdır.",


  },
  en: {
    lang: "en",
    browse: "Browse jobs",
    post: "Post a job",
    ecosystemLine: "Part of the Ingress ecosystem",
    ecosystemLinkLabel: "Ingress Academy",
    ecosystemFooter: "Ingress Job is the job board in the Ingress ecosystem. Sign-in uses your Ingress Academy account.",
    openRole: "Open",
    allCities: "All cities",
    count: (n) => `${n} ${n === 1 ? "job" : "jobs"}`,
    pagePrev: "Previous",
    pageNext: "Next",
    pageOf: (page, total) => `Page ${page} / ${total}`,
    empty: "No roles match this filter.",
    loadError: "Jobs could not be loaded. Check that the API is running.",
    noCompany: "Company not listed",
    noCity: "City not listed",
    source: "Source",
    back: "Back to jobs",
    breadcrumbs: "Breadcrumb",
    breadcrumbHome: "Jobs",
    faq: {
      eyebrow: "Questions",
      title: "Common questions",
      items: [
        {
          q: "What is Ingress Job?",
          a: "Ingress Job is a board of open roles in Azerbaijan and part of the Ingress ecosystem. Search and filter by title, company, city, language, and salary.",
        },
        {
          q: "How does it relate to Ingress?",
          a: "Ingress Job is a product in the Ingress family. Sign-in and registration use your Ingress Academy account — the same account can work across other products in the ecosystem.",
        },
        {
          q: "Is browsing free?",
          a: "Yes. You can read open listings without an account. Applying and posting require an Ingress Academy account.",
        },
        {
          q: "How do I search and filter?",
          a: "Search by title or company, then narrow the list by city, source, language, date, remote work, and salary range.",
        },
        {
          q: "Do I need an account to apply?",
          a: "Yes. Register as a candidate to apply to a role and track your applications.",
        },
        {
          q: "How do I post a job?",
          a: "Register as an employer, save your company profile, then write the ad. Listings go through moderation before they go public.",
        },
        {
          q: "Are remote jobs included?",
          a: "Yes. You can filter for remote or city-less roles; hybrid and office listings are in the list too.",
        },
        {
          q: "Where do listings come from?",
          a: "The board may include ads written on the platform and open listings gathered from other sources. Each job shows its source.",
        },
        {
          q: "Which languages can I use?",
          a: "The site is available in Azerbaijani, English, and Russian. A listing’s own language may differ — use the language filter.",
        },
      ],
    },
    apply: "Apply",
    original: "Original listing",
    locked: "An account is required. The address is not shown here.",
    missing: "This job was not found.",
    postTitle: "Employer cabinet",
    postBody: "Register to write a job ad.",
    postCandidateTitle: "Posting jobs is for company accounts",
    postCandidateBody: "You are signed in with a candidate account. Job ads can be posted by employer (company) accounts and Ingress staff.",
    postBecomeEmployer: "Continue with a company account",
    postBackToJobs: "Back to jobs",
    description: "Description",
    sources: "Source",
    companies: "Company",
    companyPlaceholder: "Company name",
    remoteFilter: "Remote work",
    relocationFilter: "Relocation or visa support",
    relocationBadge: "Relocation / visa",
    techStack: "Tech stack",
    techPlaceholder: "Find a technology",
    categoryFilter: "Category",
    sourceSite: "Source site",
    navCompanies: "Companies",
    navTrends: "Trends",
    trendsTitle: "Skill trends",
    trendsLede: "Skill demand share and week-over-week change in the listings we track.",
    trendsEmpty: "No trend data yet. It appears after the worker builds the daily aggregates.",
    trendsShare: "Share",
    trendsGrowth: "WoW growth",
    trendsAds: "Ads",
    trendsAdsCount: (n) => `${n} ${n === 1 ? "ad" : "ads"}`,
    trendsSalaryLabel: "Median salary",
    trendsSalary: (median, currency) => `Median salary: ${median} ${currency}/year`,
    trendsSalaryMedian: (median, currency) => `${median} ${currency}/year`,
    trendsSalaryRange: (low, high, currency) => `${low}–${high} ${currency}`,
    trendsSalaryN: (n) => `Based on ${n} ads`,
    trendsOftenWith: "Often with",
    trendsOftenWithItem: (name, pct) => `${name} (${pct}%)`,
    trendsAsOf: (day) => `As of ${day}`,
    trendsAsOfLabel: "As of",
    trendsWindow: (n) => `Last ${n} days`,
    trendsWindowLabel: "Period",
    trendsWindowPrefix: "Last",
    trendsWindowUnit: "days",
    trendsWindowApply: "Show",
    trendsDisclaimer: "Trends reflect only listings Ingress Job tracks — not the whole market.",
    trendsDetailKicker: "Skill trend",
    trendsDetailBack: "Back to trends",
    trendsDetailJobs: "Jobs that require this skill",
    trendsDetailJobsBack: "Back to trend",
    trendsDetailJobsEmpty: "No open jobs found for this skill.",
    trendsDetailYou: "You vs this trend",
    trendsDetailHaveFocus: "This skill is on your profile.",
    trendsDetailMissingFocus: "This skill is not on your profile yet.",
    trendsDetailCompanionsHave: "Companion skills you already have",
    trendsDetailCompanionsLearn: "Learn to reach this demand",
    trendsDetailGuest: "Sign in as a candidate to compare with your profile.",
    trendsDetailGuestCta: "Sign in / register",
    trendsDetailNotFound: "No trend found for this skill.",
    companiesTitle: "Companies",
    companiesLede: "Jobs, tech and applications by company",
    companiesSearch: "Search companies",
    companiesSearchButton: "Search",
    sortMostJobs: "Most jobs",
    sortAZ: "A–Z",
    sortMostApplications: "Most applications",
    companiesEmpty: "No companies match this search.",
    companiesEmptyAll: "No companies with open jobs yet.",
    companiesReset: "All companies",
    companiesLoading: "Loading companies…",
    openJobs: (n) => `${n} open ${n === 1 ? "job" : "jobs"}`,
    statOpenJobs: "Open jobs",
    statApplications: "Applications",
    statPerJob: "Per job",
    statPopularity: "Popularity",
    popularityHelp: "Popularity: this company's share of all applications sent through this site to open jobs on the platform.",
    statLocations: "Locations",
    statRemoteShare: "Remote share",
    remoteJobs: (n) => `${n} remote`,
    relocationJobs: (n) => `${n} with relocation`,
    companyJobs: "Open jobs at this company",
    companyCategories: "Categories",
    latestPosted: "Latest job",
    applicationsCount: (n) => `${n} ${n === 1 ? "application" : "applications"}`,
    applicationsNone: "No applications yet — be the first",
    applicationsFirst: "Be the first to apply",
    applicationsNote: "Only applications sent through this site are counted.",
    keyFacts: "Key facts",
    factLocation: "Location",
    factPosted: "Posted",
    salaryFilter: "Salary",
    salaryMin: "Minimum",
    salaryMax: "Maximum",
    salaryNote: "Includes negotiable / by agreement",
    clear: "Clear filters",
    filters: "Filters",
    filtersApply: "Apply",
    filtersClear: "Clear",
    filtersClose: "Close filters",
    filtersActive: (n) => `${n} active ${n === 1 ? "filter" : "filters"}`,
    menuOpen: "Open menu",
    menuClose: "Close menu",
    menuLabel: "Menu",
    sort: "Sort",
    newest: "Newest",
    oldest: "Oldest",
    byTitle: "By title",
    when: "Date",
    anyTime: "Any time",
    today: "Today",
    week: "Last 7 days",
    language: "Listing language",
    langAz: "Azerbaijani",
    langEn: "English",
        langRu: "Russian",
    register: "Register",
    registerAsk: "With an Ingress Academy account: posting a job, or applying?",
    registerEmployerUpgrade: "Want to post jobs as an employer too?",
    registerPoster: "Posting a job",
    registerCreator: "Applying",
    signOut: "Sign out",
    roleEmployer: "Employer",
    roleCandidate: "Candidate",
    roleStaff: "Staff",
    companyTitle: "Company profile",
    companyLede: "Save the company name, city, and a short description before posting. Edit them later on the Profile page.",
    companyName: "Company name",
    companyCity: "City",
    companyAbout: "Short description",
    companySave: "Save",
    companyRequired: "Company name, city, and a short description are required.",
    companySaved: "Company profile saved.",
    companyEditOnProfile: "Your company profile is complete. Edit it on the Profile page.",
    companyGoProfile: "Go to Profile",
    ssoError: "Sign-in did not finish. Try again.",
    account: "Account",
    accountSignedIn: "Signed in",
    cabinetLede: "Write, edit, and close your own ads. A company ad stays off the public list until it is approved. After publication, a change to the title, text, company, city, or language sends it back to moderation.",
    cabinetEmpty: "You have no ads yet.",
    newAd: "New ad",
    editAd: "Edit ad",
    myAds: "My ads",
    cabinetApplicationsTab: "Applications",
    ownerApplicationsAll: "All applications",
    adTitle: "Title",
    adBody: "Text",
    adSalary: "Salary",
    adOptional: "Optional",
    adJobType: "Job type",
    adJobTypeNone: "Not selected",
    jobOffice: "Office",
    jobHybrid: "Hybrid",
    jobRemoteType: "Remote",
    placeRemote: "Remote",
    adCityOrRemote: "City or remote",
    adSave: "Save",
    adClose: "Close",
    adCloseAsk: "Close this ad? It leaves the public list.",
    adEdit: "Edit",
    adCancel: "Cancel",
    adRequired: "Title, company, city or remote, and the text are required.",
    adSavedPending: "The ad was sent for moderation.",
    adSavedLive: "The ad is published.",
    adClosedNote: "The ad is closed.",
    statusPending: "In moderation",
    statusPublished: "Published",
    statusClosed: "Closed",
    companyLocked: "The company name comes from the saved profile.",
    cannotEdit: "An approved ad can no longer be edited.",
    cabinetError: "The ad could not be saved.",
    statusRejected: "Rejected",
    admin: "Moderation",
    adminTitle: "Ad moderation",
    adminLede: "Reject pending ads with a reason, or approve and close them. Edit, hide, or merge collected ads.",
    adminGate: "Moderation is only for staff accounts.",
    adminQueue: "Ad queue",
    adminEmpty: "There are no ads to moderate.",
    adminApprove: "Approve",
    adminReject: "Reject",
    adminRejectAsk: "Write the rejection reason. If you leave it empty, the ad is not rejected.",
    adminApprovedNote: "The ad is published.",
    adminRejectedNote: "The ad was rejected.",
    adminSavedNote: "Changes saved.",
    adminError: "The action could not be completed.",
    rejectReason: "Rejection reason",
    rejectReasonRequired: "A rejection reason is required.",
    resubmitHint: "Saving a rejected ad sends it back to moderation and keeps it off the public list.",
    reviewHint: "Changing the title, text, company, city, remote flag, or language sends the ad back to moderation. Salary and job type alone stay published.",
    cannotChange: "This ad can no longer be changed.",
    collectedTitle: "Collected ads",
    collectedLede: "Edit an automatically collected ad, hide it from the public site, or merge two duplicates.",
    collectedEmpty: "There are no collected ads.",
    collectedHide: "Hide",
    collectedShow: "Show",
    collectedHidden: "Hidden",
    collectedKeep: "Keep this one",
    collectedMerge: "Hide as duplicate",
    collectedMerged: "Merged",
    collectedMergeNote: "The duplicate is hidden. The kept ad stays visible.",
    collectedHideNote: "The ad is hidden from the public site.",
    collectedShowNote: "The ad is on the public list again.",
    collectedKept: "Kept ad selected.",
    manualTitle: "Manual source link",
    manualLede: "Add an ad that was not collected automatically, such as LinkedIn, with the required fields and the original URL. Guests never see that URL.",
    manualUrl: "Original URL",
    manualSaved: "The ad is published. The URL opens only after registration.",
    manualUrlInvalid: "The original URL must be http or https.",
    applyMessage: "Short message",
    applyCv: "CV",
    applyCvHint: "PDF, DOC, or DOCX, up to 5 MB.",
    applySend: "Send application",
    applySent: "Application sent.",
    applyRequired: "A short message is required.",
    applyDuplicate: "You already applied to this ad.",
    applyError: "The application could not be sent.",
    myApplications: "My applications",
    savedJobs: "Saved jobs",
    savedJobsLede: "Jobs you saved to review later.",
    savedJobsEmpty: "No saved jobs yet.",
    savedJobsGate: "Saved jobs need a signed-in account.",
    saveJob: "Save job",
    unsaveJob: "Remove from saved",
    saveJobError: "Could not update saved jobs.",
    talentTitle: "Talent search",
    talentLede: "Browse confirmed candidates who opted into recruiter visibility. Contact requests are not available yet.",
    talentSearch: "Search",
    talentSearchLabel: "Search",
    talentSearchPlaceholder: "Headline, skill, or seniority",
    talentEmpty: "No matching candidates.",
    talentGateGuest: "Talent search needs an employer account.",
    talentGateRole: "This page is for employer and staff accounts only.",
    talentGateCompany: "Complete your company profile first.",
    talentAnonymous: "Anonymous candidate",
    talentVisibilityAnonymous: "Anonymous",
    talentVisibilityPublic: "Open profile",
    talentYears: (n) => `${n} years experience`,
    applicationsTitle: "Applications",
    adminAiTitle: "AI flows",
    adminAiLede: "Turn each flow on or off on its own. You do not need to delete the API key; calls stop while the key stays set.",
    adminAiNoKey: "OPENAI_API_KEY is not set. Toggles are saved, but no model calls are sent.",
    adminAiGateway: "Shared AI gateway (LLM and embeddings)",
    adminAiCv: "CV parse fallback (AI #1)",
    adminAiTidy: "Job-text tidy",
    adminAiEmbeddings: "Job and profile embeddings",
    adminAiRerank: "Match rerank (AI #2)",
    adminAiLlmRerank: "LLM match re-rank (top-10)",
    adminAiWhy: "Match “why” sentence",
    adminAiRoleCoach: "Role skill coach",
    adminAiDigest: "Digest intro (AI #4)",
    adminAiEngagement: "Engagement notification copy",
    adminAiSaved: "AI settings saved.",
    applicationsEmpty: "There are no applications yet.",
    downloadCv: "Open CV",
    noCv: "No CV",
    ownerApplications: "Applications for this ad",
    applyPhone: "Phone",
    applyEmail: "Email",
    applyFieldRequired: "Fill in the required fields.",
    applyPhoneInvalid: "The phone number is not valid.",
    applyEmailInvalid: "The email is not valid.",
    applyCvRequired: "The CV must be a PDF, DOC, or DOCX file of up to 5 MB.",
    formTitle: "Application form",
    formLede: "The applicant fills only the fields you select. Each field is required or optional. Up to 5 questions of your own. You can change the form after the ad is published; older applications keep the answers already stored.",
    fieldRequired: "Required",
    formQuestion: "Your question",
    formAddQuestion: "Add a question",
    formRemoveQuestion: "Remove",
    formNeedField: "Select at least one field.",
    formQuestionNeeded: "Write the question.",
    appSubmitted: "submitted",
    appSeen: "seen",
    appRejected: "rejected",
    appWithdraw: "Withdraw",
    appWithdrawAsk: "Withdraw this application? You can apply again afterwards.",
    appSeenAction: "Mark as seen",
    appRejectAction: "Reject",
    appRejectAsk: "A rejection reason is optional. If you leave it empty, the applicant does not see a reason.",
    appUpdated: "Status updated.",
    appWithdrawn: "Application withdrawn.",
    appStatusError: "The status could not be changed.",
    appTimelineLabel: "Status history",
    appEmployerNote: "Note: ",
    myApplicationsLede: "Status and employer notes for applications you sent.",
    applicationsGate: "Applications need a candidate account.",
    languageAuto: "Automatic",
    profileTitle: "Profile",
    profileLede: "These details stay on the job site. Academy account settings do not open.",
    profileOpen: "Open profile",
    profileCompanyLede: "Company name, city, and a short description. Saving updates this profile.",
    profileApplicantTitle: "Applicant profile",
    profileApplicantLede: "Display name, phone, and email stay on the job site. If an application asks for phone or email and that field is empty, it is filled from here. You can still change it on that application.",
    profileCvCtaLede: "Fill in your full CV profile for skills, experience, and recommendations.",
    profileName: "Display name",
    profileNameRequired: "Enter a display name.",
    profileSaved: "Profile saved.",
    privacyTitle: "Privacy and consents",
    privacyLede: "Separate choices for CV analysis, emails, and recruiter visibility. All are off by default.",
    privacySaved: "Consents saved.",
    privacyError: "Consents could not be saved.",
    privacyExportError: "Could not download your data.",
    privacyDeleteConfirm: "All your candidate data (profile, CV, consents) will be deleted. Continue?",
    privacyDeleteDone: "Your data was deleted.",
    privacyDeleteError: "Could not delete your data.",
    privacyWhoViewedSoon: "This feature is coming soon.",
    profileGate: "The profile is for an employer, applicant, or staff account.",
    profileReviewTitle: "Review CV profile",
    profileReviewLede: "Upload a CV to auto-fill fields, or enter them yourself. Everything stays editable.",
    profileReviewOpen: "Review CV profile",
    profileReviewEmpty: "No profile yet. Upload a CV or fill the form manually.",
    profileReviewPending: "Fields will fill in automatically when ready.",
    profileReviewFailed: "The last CV parse failed. Upload again or fill the form manually.",
    profileReviewCancelParse: "Cancel",
    profileReviewCancelDone: "CV analysis cancelled. Upload again or fill the form manually.",
    profileReviewStalled: "Analysis is taking too long. Cancel and upload again, or fill the form manually.",
    profileReviewChooserTitle: "How do you want to start?",
    profileReviewChooserLede: "You can review and edit anything extracted from a CV.",
    profileReviewOptionUpload: "Upload CV",
    profileReviewOptionUploadHint: "PDF, DOC, or DOCX — we extract the details.",
    profileReviewOptionManual: "Fill manually",
    profileReviewOptionManualHint: "Opens an empty form you can edit freely.",
    profileReviewUploadTitle: "CV source",
    profileReviewUploadHint: "PDF, DOC, or DOCX, up to 5 MB. You can edit the form after upload.",
    profileReviewUploadCta: "Choose CV",
    profileReviewReuploadCta: "Replace CV",
    profileReviewUploading: "Uploading…",
    profileReviewUploadQueued: "CV received. Parsing…",
    profileReviewUploadError: "Could not upload the CV.",
    profileReviewUploadedName: (name) => `Last upload: ${name}`,
    profileReviewFilledFromCv: "Filled from your CV. Edit anything that looks wrong, then confirm.",
    profileReviewManualBadge: "Manual entry",
    profileReviewProgressTitle: "Analyzing CV",
    profileReviewStepUpload: "Upload",
    profileReviewStepQueue: "Queue",
    profileReviewStepParse: "Extract",
    profileReviewBasics: "Basics",
    profileReviewTabBasics: "Basics",
    profileReviewTabExperience: "Experience",
    profileReviewTabMore: "Education & languages",
    profileReviewCheck: "Low confidence from CV — review",
    profileReviewHeadline: "Headline",
    profileReviewAbout: "About",
    profileReviewAboutHint: "A short intro — experience, focus, and goals.",
    profileReviewSeniority: "Seniority",
    profileReviewYears: "Total experience (years)",
    profileReviewSkills: "Skills",
    profileReviewSkillsEmpty: "No skills yet.",
    profileReviewSkillAdd: "Add",
    profileReviewSkillName: "Skill",
    profileReviewSkillYears: "yr",
    profileReviewSkillEdit: "Tap to edit",
    profileReviewWork: "Work history",
    profileReviewWorkEmpty: "No work history yet.",
    profileReviewWorkAdd: "Add job",
    profileReviewWorkItem: (n) => `Job #${n}`,
    profileReviewRemove: "Remove",
    profileReviewJobTitle: "Title",
    profileReviewCompany: "Company",
    profileReviewLocation: "Location",
    profileReviewJobSummary: "Description",
    profileReviewStart: "Start",
    profileReviewEnd: "End",
    profileReviewPresent: "present",
    profileReviewEducation: "Education",
    profileReviewEducationEmpty: "No education yet.",
    profileReviewEducationAdd: "Add education",
    profileReviewEducationItem: (n) => `Education #${n}`,
    profileReviewDegree: "Degree",
    profileReviewField: "Field",
    profileReviewSchool: "School / University",
    profileReviewEduYear: "Year",
    profileReviewLanguages: "Languages",
    profileReviewLanguagesEmpty: "No languages yet.",
    profileReviewLanguageAdd: "Add language",
    profileReviewLangCode: "Language",
    profileReviewLangLevel: "Level",
    profileReviewLangNative: "Native",
    profileReviewLangLabel: (code) =>
      ({ az: "Azerbaijani", en: "English", ru: "Russian", tr: "Turkish", de: "German", fr: "French" }[code] ||
      code),
    profileReviewLinks: "Links",
    profileReviewLinkedin: "LinkedIn",
    profileReviewGithub: "GitHub",
    profileReviewPortfolio: "Portfolio / website",
    profileReviewContact: "Contact",
    profileReviewFullName: "Name",
    profileReviewCity: "City",
    profileReviewCountry: "Country",
    profileReviewStatusDraft: "Draft",
    profileReviewStatusConfirmed: "Confirmed",
    profileReviewConfidence: (n) => `Confidence: ${Math.round(n * 100)}%`,
    profileReviewSave: "Save",
    profileReviewConfirm: "Confirm profile",
    profileReviewReset: "Reset",
    profileReviewResetConfirm: "This will clear your profile. You can upload a CV or fill the form again. Continue?",
    profileReviewResetDone: "Profile reset.",
    profileReviewResetError: "Could not reset the profile.",
    profileReviewSaved: "Profile saved.",
    profileReviewConfirmed: "Profile confirmed.",
    profileReviewError: "The profile could not be saved.",
    profileReviewRolesTitle: "Suggested roles",
    profileReviewRolesEmpty: "No role suggestions yet. Add skills and save.",
    profileReviewRolesConsent: "Turn on matching consent to see role suggestions.",
    profileReviewRolesConsentLink: "Privacy settings",
    profileReviewRolesScore: (n) => `${Math.round(n * 100)}%`,
    recommendationsOpen: "Recommendations",
    recommendationsTitle: "Recommendations",
    recommendationsLede: "Pick a role — what to learn next, what you have, and matching jobs.",
    recommendationsDisclaimer: "Scores are rules-based; AI re-ranking and explanations may apply when enabled.",
    recommendationsGate: "Recommendations require a candidate account.",
    recommendationsConsent: "Turn on matching consent to see recommendations.",
    recommendationsConsentLink: "Privacy settings",
    recommendationsRoles: "Suggested roles",
    recommendationsSelectedRole: "Selected role",
    recommendationsJobs: "Matching jobs",
    recommendationsEmptyRoles: "No role suggestions yet. Add skills to your profile.",
    recommendationsEmptyJobs: "No matching jobs yet. Complete your profile or check back later.",
    recommendationsScore: (n) => `${Math.round(n * 100)}%`,
    recommendationsUp: "Good match",
    recommendationsDown: "Not a match",
    recommendationsReason: "Reason",
    recommendationsReasonLocation: "Location",
    recommendationsReasonSeniority: "Seniority",
    recommendationsReasonTechnology: "Technology",
    recommendationsReasonSalary: "Salary",
    recommendationsGap: "Skill gap",
    recommendationsGapEmpty: "No skill gap for this role.",
    recommendationsGapLearn: "Learn next",
    recommendationsGapShare: (pct) => `${pct}% share`,
    recommendationsGapGrowth: (pct) => `${pct > 0 ? "+" : ""}${pct}% WoW`,
    recommendationsGapGrowthSurge: "Sharp rise",
    recommendationsGapGrowthDrop: "Sharp drop",
    recommendationsGapOftenWith: (base, pct) => `Required in ~${pct}% of ${base} ads`,
    recommendationsFeedbackSaved: "Feedback saved.",
    recommendationsFeedbackError: "Could not save feedback.",
    recommendationsGapCourse: "Academy course",
    recommendationsGapCareerPath: "Academy career path",
    recommendationsGapLink: "Skill gap and Academy courses",
    skillsOpen: "Skills",
    skillsTitle: "Skills and gaps",
    skillsLede: "Pick a role — what you have, what to learn next, and Academy courses.",
    skillsGate: "Skill analysis requires a candidate account.",
    skillsTargetRole: "Target role",
    skillsHave: "You have",
    skillsMissing: "Missing",
    skillsHaveCount: (n) => `${n} have`,
    skillsMissingCount: (n) => `${n} missing`,
    skillsHaveEmpty: "No confirmed skills for this role.",
    skillsMissingEmpty: "No missing skills for this role.",
    skillsCoachTitle: "Role coach",
    skillsCoachMustLearn: "Learn first",
    skillsCoachStrong: "Already strong",
    skillsCoachTransferable: "Transferable skills",
    skillsCoachTransfer: (from, to) => `${from} → ${to}`,
    recommendationsCoachMore: "Full coach advice",
    insightsOpen: "Insights",
    insightsTitle: "This week’s insights",
    insightsLede: "Learning plan, near-miss jobs, and Academy tips — in one place.",
    insightsGate: "Insights require a candidate account.",
    insightsCoachTitle: "Weekly learning plan",
    insightsCoachRole: (role) => `Role: ${role}`,
    insightsCoachEmpty: "No coach plan yet. Confirm your profile and turn on matching consent.",
    insightsNearTitle: "Near-miss jobs",
    insightsNearEmpty: "No near-miss jobs yet.",
    insightsGrowthTitle: "Learning path",
    insightsGrowthEmpty: "No Academy or roadmap tips yet.",
    noticeCtaOpen: "Open",
    noticeCtaLearn: "Learn",
    noticeCtaInsights: "Insights",
    noticeCtaProfile: "Complete profile",
    noticeRoadmapTitle: "Learning steps",
    noticeComingSoon: "Ingress training coming soon",
    emailSettingsOpen: "Notification settings",
    emailSettingsTitle: "Notification settings",
    emailSettingsLede: "Email digests, match alerts, and push. Transactional mail stays separate.",
    emailSettingsGate: "Notification settings require a candidate account.",
    emailSettingsPrivacyLink: "Privacy and consents",
    emailSettingsConsentOff: "Marketing email consent is off.",
    emailSettingsFrequency: "Frequency",
    emailSettingsLanguage: "Email language",
    emailSettingsWeekday: "Send day",
    emailSettingsDigest: "Weekly / biweekly digest",
    emailSettingsHighMatch: "High-match alerts",
    emailSettingsMatchNear: "Near-miss jobs (skill-growth tips)",
    emailSettingsProfileNudge: "Profile completion reminders",
    emailSettingsCoachWeekly: "Weekly learning plan",
    emailSettingsPush: "Browser push notifications (master)",
    emailSettingsPushEnable: "Allow browser notifications",
    emailSettingsPushDisable: "Remove push subscription",
    emailSettingsPushHint:
      "Needs browser permission and a subscription. On iOS, only installed PWA over HTTPS.",
    emailSettingsPushOn: "Browser push is active.",
    emailSettingsPushDenied: "Notification permission was denied. You can enable it in browser settings.",
    emailSettingsPushUnsupported: "This browser does not support Web Push.",
    emailSettingsPushVapid: "Push is not configured on the server (VAPID).",
    emailSettingsPushError: "Could not subscribe to push.",
    emailSettingsSaved: "Notification settings saved.",
    emailSettingsError: "Could not save settings.",
    emailFreqWeekly: "Weekly",
    emailFreqBiweekly: "Every two weeks",
    emailFreqImportant: "Important only",
    emailFreqNone: "None",
    emailWeekdayMon: "Monday",
    emailWeekdayTue: "Tuesday",
    emailWeekdayWed: "Wednesday",
    emailWeekdayThu: "Thursday",
    emailWeekdayFri: "Friday",
    emailWeekdaySat: "Saturday",
    emailWeekdaySun: "Sunday",
    unsubscribeTitle: "Unsubscribe",
    unsubscribeLede: "Stop marketing and recommendation emails?",
    unsubscribeConfirm: "Unsubscribe",
    unsubscribeManage: "Manage email settings",
    unsubscribeDone: "You are unsubscribed. Transactional mail (for example application status) may still be sent.",
    unsubscribeInvalid: "This link is invalid or expired.",
    unsubscribeLoading: "Checking…",
    notifications: "Notifications",
    notificationsTitle: "Notifications",
    notificationsEmpty: "There are no notifications.",
    notificationsGate: "Sign in to see notifications.",
    notificationsUnread: (n) => `Notifications, ${n} unread`,
    markRead: "Mark as read",
    markAllRead: "Mark all as read",
    noteApplicationNew: (title) => `A new application arrived for «${title}».`,
    noteApplicationSeen: (title) => `Your application for «${title}» was seen.`,
    noteApplicationRejected: (title) => `Your application for «${title}» was rejected.`,
    noteAdApproved: (title) => `Your ad «${title}» was approved.`,
    noteAdRejected: (title) => `Your ad «${title}» was rejected.`,
    noteAdReview: (title) => `Your ad «${title}» is back in review after an edit.`,
    noteMatchNew: (title) => `New match for you: «${title}».`,
    noteMatchNear: (title) => `Almost a match — grow a skill: «${title}».`,
    noteProfileNudge: () => "Complete your profile — CV and skills help us find matches.",
    noteCoachWeekly: () => "This week’s learning plan is ready.",


  },
  ru: {
    lang: "ru",
    browse: "Смотреть вакансии",
    post: "Разместить вакансию",
    ecosystemLine: "Часть экосистемы Ingress",
    ecosystemLinkLabel: "Ingress Academy",
    ecosystemFooter: "Ingress Job — площадка вакансий в экосистеме Ingress. Вход через аккаунт Ingress Academy.",
    openRole: "Открыть",
    allCities: "Все города",
    count: (n) => `${n} ${n % 10 === 1 && n % 100 !== 11 ? "вакансия" : n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 10 || n % 100 >= 20) ? "вакансии" : "вакансий"}`,
    pagePrev: "Назад",
    pageNext: "Дальше",
    pageOf: (page, total) => `Страница ${page} / ${total}`,
    empty: "По этому фильтру вакансий нет.",
    loadError: "Не удалось загрузить вакансии. Проверьте, что API запущен.",
    noCompany: "Компания не указана",
    noCity: "Город не указан",
    source: "Источник",
    back: "К вакансиям",
    breadcrumbs: "Навигация",
    breadcrumbHome: "Вакансии",
    faq: {
      eyebrow: "Вопросы",
      title: "Частые вопросы",
      items: [
        {
          q: "Что такое Ingress Job?",
          a: "Ingress Job — площадка открытых вакансий в Азербайджане и часть экосистемы Ingress. Ищите и фильтруйте по должности, компании, городу, языку и зарплате.",
        },
        {
          q: "Как это связано с Ingress?",
          a: "Ingress Job — продукт семейства Ingress. Вход и регистрация идут через аккаунт Ingress Academy — тот же аккаунт можно использовать в других продуктах экосистемы.",
        },
        {
          q: "Просмотр бесплатный?",
          a: "Да. Открытые вакансии можно читать без аккаунта. Для отклика и размещения нужен аккаунт Ingress Academy.",
        },
        {
          q: "Как искать и фильтровать?",
          a: "Ищите по должности или компании, затем сужайте список по городу, источнику, языку, дате, удалённой работе и диапазону зарплаты.",
        },
        {
          q: "Нужен ли аккаунт для отклика?",
          a: "Да. Зарегистрируйтесь как кандидат — тогда сможете откликаться и следить за откликами.",
        },
        {
          q: "Как разместить вакансию?",
          a: "Зарегистрируйтесь как работодатель, заполните профиль компании и напишите объявление. Перед публикацией оно проходит модерацию.",
        },
        {
          q: "Есть ли удалённые вакансии?",
          a: "Да. Можно отфильтровать удалённые или без города; гибрид и офис тоже есть в списке.",
        },
        {
          q: "Откуда берутся вакансии?",
          a: "В списке могут быть объявления с платформы и открытые вакансии из других источников. У каждой вакансии указан источник.",
        },
        {
          q: "На каких языках можно пользоваться?",
          a: "Сайт доступен на азербайджанском, английском и русском. Язык самой вакансии может отличаться — используйте фильтр языка.",
        },
      ],
    },
    apply: "Откликнуться",
    original: "Оригинал",
    locked: "Нужен аккаунт. Адрес здесь не показывается.",
    missing: "Вакансия не найдена.",
    postTitle: "Кабинет работодателя",
    postBody: "Чтобы написать объявление, зарегистрируйтесь.",
    postCandidateTitle: "Размещать вакансии могут только компании",
    postCandidateBody: "Вы вошли как соискатель. Публиковать вакансии могут аккаунты работодателей (компаний) и сотрудники Ingress.",
    postBecomeEmployer: "Продолжить как компания",
    postBackToJobs: "Вернуться к вакансиям",
    description: "Описание",
    sources: "Источник",
    companies: "Компания",
    companyPlaceholder: "Название компании",
    remoteFilter: "Удалённая работа",
    relocationFilter: "Релокация или визовая поддержка",
    relocationBadge: "Релокация / виза",
    techStack: "Технологии",
    techPlaceholder: "Найти технологию",
    categoryFilter: "Категория",
    sourceSite: "Сайт источника",
    navCompanies: "Компании",
    navTrends: "Тренды",
    trendsTitle: "Тренды навыков",
    trendsLede: "Доля спроса на навыки и недельное изменение в отслеживаемых вакансиях.",
    trendsEmpty: "Пока нет данных о трендах. Они появятся после ежедневной агрегации worker.",
    trendsShare: "Доля",
    trendsGrowth: "Рост за неделю",
    trendsAds: "Вакансии",
    trendsAdsCount: (n) => `${n} ${ruPlural(n, "вакансия", "вакансии", "вакансий")}`,
    trendsSalaryLabel: "Медианная зарплата",
    trendsSalary: (median, currency) => `Медианная зарплата: ${median} ${currency}/год`,
    trendsSalaryMedian: (median, currency) => `${median} ${currency}/год`,
    trendsSalaryRange: (low, high, currency) => `${low}–${high} ${currency}`,
    trendsSalaryN: (n) => `На основе ${n} вакансий`,
    trendsOftenWith: "Часто вместе",
    trendsOftenWithItem: (name, pct) => `${name} (${pct}%)`,
    trendsAsOf: (day) => `На ${day}`,
    trendsAsOfLabel: "Дата",
    trendsWindow: (n) => `За ${n} дн.`,
    trendsWindowLabel: "Период",
    trendsWindowPrefix: "За",
    trendsWindowUnit: "дн.",
    trendsWindowApply: "Показать",
    trendsDisclaimer: "Тренды считаются только по вакансиям, которые отслеживает Ingress Job, а не по всему рынку.",
    trendsDetailKicker: "Тренд навыка",
    trendsDetailBack: "Назад к трендам",
    trendsDetailJobs: "Вакансии, где требуется этот навык",
    trendsDetailJobsBack: "К тренду",
    trendsDetailJobsEmpty: "Открытых вакансий с этим навыком нет.",
    trendsDetailYou: "Вы и этот тренд",
    trendsDetailHaveFocus: "Этот навык есть в вашем профиле.",
    trendsDetailMissingFocus: "Этого навыка пока нет в вашем профиле.",
    trendsDetailCompanionsHave: "Сопутствующие навыки, которые у вас есть",
    trendsDetailCompanionsLearn: "Чему учиться, чтобы соответствовать спросу",
    trendsDetailGuest: "Войдите как кандидат, чтобы сравнить с профилем.",
    trendsDetailGuestCta: "Войти / регистрация",
    trendsDetailNotFound: "Тренд для этого навыка не найден.",
    companiesTitle: "Компании",
    companiesLede: "Вакансии, технологии и отклики по компаниям",
    companiesSearch: "Поиск компании",
    companiesSearchButton: "Найти",
    sortMostJobs: "Больше вакансий",
    sortAZ: "А–Я",
    sortMostApplications: "Больше откликов",
    companiesEmpty: "Компании по этому запросу не найдены.",
    companiesEmptyAll: "Пока нет компаний с открытыми вакансиями.",
    companiesReset: "Все компании",
    companiesLoading: "Загружаем компании…",
    openJobs: (n) => `${n} ${ruPlural(n, "открытая вакансия", "открытые вакансии", "открытых вакансий")}`,
    statOpenJobs: "Открытые вакансии",
    statApplications: "Отклики",
    statPerJob: "На вакансию",
    statPopularity: "Популярность",
    popularityHelp: "Популярность: доля компании среди всех откликов, отправленных через этот сайт на открытые вакансии платформы.",
    statLocations: "Локации",
    statRemoteShare: "Доля удалённых",
    remoteJobs: (n) => `${n} удалённо`,
    relocationJobs: (n) => `${n} с релокацией`,
    companyJobs: "Открытые вакансии компании",
    companyCategories: "Категории",
    latestPosted: "Последняя вакансия",
    applicationsCount: (n) => `${n} ${ruPlural(n, "отклик", "отклика", "откликов")}`,
    applicationsNone: "Откликов пока нет — будьте первым",
    applicationsFirst: "Откликнитесь первым",
    applicationsNote: "Учитываются только отклики, отправленные через этот сайт.",
    keyFacts: "Основное",
    factLocation: "Локация",
    factPosted: "Опубликовано",
    salaryFilter: "Зарплата",
    salaryMin: "Минимум",
    salaryMax: "Максимум",
    salaryNote: "Включая зарплату по договорённости",
    clear: "Сбросить фильтры",
    filters: "Фильтры",
    filtersApply: "Применить",
    filtersClear: "Сбросить",
    filtersClose: "Закрыть фильтры",
    filtersActive: (n) => `${n} ${ruPlural(n, "активный фильтр", "активных фильтра", "активных фильтров")}`,
    menuOpen: "Открыть меню",
    menuClose: "Закрыть меню",
    menuLabel: "Меню",
    sort: "Порядок",
    newest: "Сначала новые",
    oldest: "Сначала старые",
    byTitle: "По названию",
    when: "Дата",
    anyTime: "Все",
    today: "Сегодня",
    week: "Последние 7 дней",
    language: "Язык объявления",
    langAz: "Азербайджанский",
    langEn: "Английский",
        langRu: "Русский",
    register: "Регистрация",
    registerAsk: "С аккаунтом Ingress Academy: публикуете вакансию или откликаетесь?",
    registerEmployerUpgrade: "Хотите также публиковать вакансии как работодатель?",
    registerPoster: "Публикую вакансию",
    registerCreator: "Откликаюсь",
    signOut: "Выйти",
    roleEmployer: "Работодатель",
    roleCandidate: "Кандидат",
    roleStaff: "Сотрудник",
    companyTitle: "Профиль компании",
    companyLede: "Перед публикацией сохраните название компании, город и короткое описание. Дальше правьте их на странице Профиль.",
    companyName: "Название компании",
    companyCity: "Город",
    companyAbout: "Коротко о компании",
    companySave: "Сохранить",
    companyRequired: "Нужны название компании, город и короткое описание.",
    companySaved: "Профиль компании сохранён.",
    companyEditOnProfile: "Профиль компании уже заполнен. Меняйте его на странице Профиль.",
    companyGoProfile: "К профилю",
    ssoError: "Вход не завершился. Попробуйте снова.",
    account: "Аккаунт",
    accountSignedIn: "Вы вошли",
    cabinetLede: "Пишите, правьте и закрывайте свои объявления. Объявление компании не попадает в общий список, пока его не одобрят. После публикации смена заголовка, текста, компании, города или языка снова отправляет его на модерацию.",
    cabinetEmpty: "У вас пока нет объявлений.",
    newAd: "Новое объявление",
    editAd: "Править объявление",
    myAds: "Мои объявления",
    cabinetApplicationsTab: "Отклики",
    ownerApplicationsAll: "Все отклики",
    adTitle: "Заголовок",
    adBody: "Текст",
    adSalary: "Зарплата",
    adOptional: "Необязательно",
    adJobType: "Тип работы",
    adJobTypeNone: "Не выбрано",
    jobOffice: "Офис",
    jobHybrid: "Гибрид",
    jobRemoteType: "Удалённо",
    placeRemote: "Удалённо",
    adCityOrRemote: "Город или удалённо",
    adSave: "Сохранить",
    adClose: "Закрыть",
    adCloseAsk: "Закрыть объявление? Оно уйдёт из общего списка.",
    adEdit: "Править",
    adCancel: "Отмена",
    adRequired: "Нужны заголовок, компания, город или удалённо, и текст.",
    adSavedPending: "Объявление отправлено на модерацию.",
    adSavedLive: "Объявление опубликовано.",
    adClosedNote: "Объявление закрыто.",
    statusPending: "На модерации",
    statusPublished: "Опубликовано",
    statusClosed: "Закрыто",
    companyLocked: "Название компании берётся из сохранённого профиля.",
    cannotEdit: "Одобренное объявление уже нельзя править.",
    cabinetError: "Не удалось сохранить объявление.",
    statusRejected: "Отклонено",
    admin: "Модерация",
    adminTitle: "Модерация объявлений",
    adminLede: "Отклоняйте ожидающие объявления с причиной, одобряйте или закрывайте их. Собранные объявления можно править, скрывать и объединять.",
    adminGate: "Модерация доступна только сотрудникам.",
    adminQueue: "Очередь объявлений",
    adminEmpty: "Нет объявлений для модерации.",
    adminApprove: "Одобрить",
    adminReject: "Отклонить",
    adminRejectAsk: "Напишите причину отклонения. Если оставить пустым, объявление не будет отклонено.",
    adminApprovedNote: "Объявление опубликовано.",
    adminRejectedNote: "Объявление отклонено.",
    adminSavedNote: "Изменения сохранены.",
    adminError: "Не удалось выполнить действие.",
    rejectReason: "Причина отклонения",
    rejectReasonRequired: "Нужно написать причину отклонения.",
    resubmitHint: "Сохранение отклонённого объявления снова отправляет его на модерацию и оставляет вне общего списка.",
    reviewHint: "Смена заголовка, текста, компании, города, удалённой работы или языка возвращает объявление на модерацию. Зарплата и тип работы сами по себе остаются опубликованными.",
    cannotChange: "Это объявление уже нельзя изменить.",
    collectedTitle: "Собранные объявления",
    collectedLede: "Отредактируйте автоматически собранное объявление, скройте его с сайта или объедините два дубликата.",
    collectedEmpty: "Собранных объявлений нет.",
    collectedHide: "Скрыть",
    collectedShow: "Показать",
    collectedHidden: "Скрыто",
    collectedKeep: "Оставить это",
    collectedMerge: "Скрыть как дубликат",
    collectedMerged: "Объединено",
    collectedMergeNote: "Дубликат скрыт. Оставленное объявление видно.",
    collectedHideNote: "Объявление скрыто с публичного сайта.",
    collectedShowNote: "Объявление снова в общем списке.",
    collectedKept: "Оставляемое объявление выбрано.",
    manualTitle: "Ссылка на источник вручную",
    manualLede: "Добавьте объявление, которое не собралось автоматически, например из LinkedIn: обязательные поля и исходный адрес. Гость этот адрес не видит.",
    manualUrl: "Исходный адрес",
    manualSaved: "Объявление опубликовано. Адрес открывается только после регистрации.",
    manualUrlInvalid: "Исходный адрес должен быть http или https.",
    applyMessage: "Короткое сообщение",
    applyCv: "CV",
    applyCvHint: "PDF, DOC или DOCX, не больше 5 МБ.",
    applySend: "Отправить отклик",
    applySent: "Отклик отправлен.",
    applyRequired: "Нужно короткое сообщение.",
    applyDuplicate: "Вы уже откликнулись на это объявление.",
    applyError: "Не удалось отправить отклик.",
    myApplications: "Мои отклики",
    savedJobs: "Сохранённые вакансии",
    savedJobsLede: "Вакансии, которые вы отложили на потом.",
    savedJobsEmpty: "Пока нет сохранённых вакансий.",
    savedJobsGate: "Для сохранённых вакансий нужен вход в аккаунт.",
    saveJob: "Сохранить вакансию",
    unsaveJob: "Убрать из сохранённых",
    saveJobError: "Не удалось обновить сохранённые.",
    talentTitle: "Поиск кандидатов",
    talentLede: "Смотрите подтверждённые профили кандидатов с согласием на видимость. Запросы на контакт пока недоступны.",
    talentSearch: "Искать",
    talentSearchLabel: "Поиск",
    talentSearchPlaceholder: "Заголовок, навык или уровень",
    talentEmpty: "Подходящих кандидатов нет.",
    talentGateGuest: "Для поиска кандидатов нужен аккаунт работодателя.",
    talentGateRole: "Эта страница только для работодателей и сотрудников.",
    talentGateCompany: "Сначала заполните профиль компании.",
    talentAnonymous: "Анонимный кандидат",
    talentVisibilityAnonymous: "Анонимно",
    talentVisibilityPublic: "Открытый профиль",
    talentYears: (n) => `${n} лет опыта`,
    applicationsTitle: "Отклики",
    adminAiTitle: "Потоки ИИ",
    adminAiLede: "Включайте и выключайте каждый поток отдельно. Ключ удалять не нужно: вызовы останавливаются, ключ остаётся.",
    adminAiNoKey: "OPENAI_API_KEY не задан. Переключатели сохраняются, но вызовов модели нет.",
    adminAiGateway: "Общий AI gateway (LLM и эмбеддинги)",
    adminAiCv: "Запасной разбор CV (AI #1)",
    adminAiTidy: "Очистка текста объявления",
    adminAiEmbeddings: "Эмбеддинги вакансий и профиля",
    adminAiRerank: "Переранжирование совпадений (AI #2)",
    adminAiLlmRerank: "LLM переранжирование (top-10)",
    adminAiWhy: "Фраза «почему подходит»",
    adminAiRoleCoach: "Коуч по навыкам роли",
    adminAiDigest: "Вступление дайджеста (AI #4)",
    adminAiEngagement: "Текст engagement-уведомлений",
    adminAiSaved: "Настройки ИИ сохранены.",
    applicationsEmpty: "Откликов пока нет.",
    downloadCv: "Открыть CV",
    noCv: "CV нет",
    ownerApplications: "Отклики на это объявление",
    applyPhone: "Телефон",
    applyEmail: "Эл. почта",
    applyFieldRequired: "Заполните обязательные поля.",
    applyPhoneInvalid: "Номер телефона указан неверно.",
    applyEmailInvalid: "Эл. почта указана неверно.",
    applyCvRequired: "CV должен быть файлом PDF, DOC или DOCX не больше 5 МБ.",
    formTitle: "Форма отклика",
    formLede: "Кандидат заполняет только выбранные поля. Каждое поле обязательное или необязательное. Не больше 5 своих вопросов. Форму можно менять и после публикации; старые отклики хранят уже данные ответы.",
    fieldRequired: "Обязательно",
    formQuestion: "Свой вопрос",
    formAddQuestion: "Добавить вопрос",
    formRemoveQuestion: "Удалить",
    formNeedField: "Выберите хотя бы одно поле.",
    formQuestionNeeded: "Напишите вопрос.",
    appSubmitted: "отправлен",
    appSeen: "просмотрен",
    appRejected: "отклонён",
    appWithdraw: "Отозвать",
    appWithdrawAsk: "Отозвать отклик? После этого можно откликнуться снова.",
    appSeenAction: "Просмотрен",
    appRejectAction: "Отклонить",
    appRejectAsk: "Причина отклонения необязательна. Если оставить пустым, кандидат причину не увидит.",
    appUpdated: "Статус обновлён.",
    appWithdrawn: "Отклик отозван.",
    appStatusError: "Не удалось изменить статус.",
    appTimelineLabel: "История статуса",
    appEmployerNote: "Заметка: ",
    myApplicationsLede: "Статус отправленных откликов и заметки работодателя.",
    applicationsGate: "Отклики доступны аккаунту кандидата.",
    languageAuto: "Автоматически",
    profileTitle: "Профиль",
    profileLede: "Эти данные хранятся на сайте вакансий. Настройки аккаунта Academy не открываются.",
    profileOpen: "Открыть профиль",
    profileCompanyLede: "Название компании, город и короткое описание. Сохранение обновляет этот профиль.",
    profileApplicantTitle: "Профиль кандидата",
    profileApplicantLede: "Имя, телефон и эл. почта остаются на сайте вакансий. Если форма отклика спрашивает телефон или почту, а поле пустое, оно заполняется отсюда. В этом отклике значение всё равно можно изменить.",
    profileCvCtaLede: "Заполните полный CV-профиль для навыков, опыта и рекомендаций.",
    profileName: "Отображаемое имя",
    profileNameRequired: "Напишите отображаемое имя.",
    profileSaved: "Профиль сохранён.",
    privacyTitle: "Конфиденциальность и согласия",
    privacyLede: "Отдельные настройки для анализа CV, писем и видимости для рекрутеров. По умолчанию всё выключено.",
    privacySaved: "Согласия сохранены.",
    privacyError: "Не удалось сохранить согласия.",
    privacyExportError: "Не удалось скачать ваши данные.",
    privacyDeleteConfirm: "Все данные кандидата (профиль, CV, согласия) будут удалены. Продолжить?",
    privacyDeleteDone: "Ваши данные удалены.",
    privacyDeleteError: "Не удалось удалить данные.",
    privacyWhoViewedSoon: "Эта функция скоро появится.",
    profileGate: "Профиль доступен аккаунту работодателя, кандидата или сотрудника.",
    profileReviewTitle: "Проверьте CV-профиль",
    profileReviewLede: "Загрузите CV — поля заполнятся сами — или введите данные вручную. Всё можно редактировать.",
    profileReviewOpen: "Проверить CV-профиль",
    profileReviewEmpty: "Профиля пока нет. Загрузите CV или заполните форму вручную.",
    profileReviewPending: "Когда будет готово, поля заполнятся автоматически.",
    profileReviewFailed: "Последний разбор CV не удался. Загрузите снова или заполните вручную.",
    profileReviewCancelParse: "Отменить",
    profileReviewCancelDone: "Разбор CV отменён. Загрузите снова или заполните вручную.",
    profileReviewStalled: "Разбор слишком долгий. Отмените и загрузите снова или заполните вручную.",
    profileReviewChooserTitle: "Как начать?",
    profileReviewChooserLede: "Данные из CV можно проверить и исправить.",
    profileReviewOptionUpload: "Загрузить CV",
    profileReviewOptionUploadHint: "PDF, DOC или DOCX — система извлечёт данные.",
    profileReviewOptionManual: "Заполнить вручную",
    profileReviewOptionManualHint: "Откроется пустая форма для свободного ввода.",
    profileReviewUploadTitle: "Источник CV",
    profileReviewUploadHint: "PDF, DOC или DOCX, до 5 МБ. После загрузки форму можно править.",
    profileReviewUploadCta: "Выбрать CV",
    profileReviewReuploadCta: "Обновить CV",
    profileReviewUploading: "Загрузка…",
    profileReviewUploadQueued: "CV принято. Идёт разбор…",
    profileReviewUploadError: "Не удалось загрузить CV.",
    profileReviewUploadedName: (name) => `Последняя загрузка: ${name}`,
    profileReviewFilledFromCv: "Данные заполнены из CV. Исправьте при необходимости и подтвердите.",
    profileReviewManualBadge: "Ручной ввод",
    profileReviewProgressTitle: "Разбор CV",
    profileReviewStepUpload: "Загрузка",
    profileReviewStepQueue: "Очередь",
    profileReviewStepParse: "Разбор",
    profileReviewBasics: "Основное",
    profileReviewTabBasics: "Основное",
    profileReviewTabExperience: "Опыт",
    profileReviewTabMore: "Образование и языки",
    profileReviewCheck: "Слабо прочитано из CV — проверьте",
    profileReviewHeadline: "Заголовок",
    profileReviewAbout: "О себе",
    profileReviewAboutHint: "Кратко о себе — опыт, направление, цели.",
    profileReviewSeniority: "Уровень",
    profileReviewYears: "Общий опыт (лет)",
    profileReviewSkills: "Навыки",
    profileReviewSkillsEmpty: "Навыков пока нет.",
    profileReviewSkillAdd: "Добавить",
    profileReviewSkillName: "Навык",
    profileReviewSkillYears: "лет",
    profileReviewSkillEdit: "Нажмите, чтобы изменить",
    profileReviewWork: "Опыт работы",
    profileReviewWorkEmpty: "Опыта работы пока нет.",
    profileReviewWorkAdd: "Добавить работу",
    profileReviewWorkItem: (n) => `Работа #${n}`,
    profileReviewRemove: "Удалить",
    profileReviewJobTitle: "Должность",
    profileReviewCompany: "Компания",
    profileReviewLocation: "Локация",
    profileReviewJobSummary: "Описание",
    profileReviewStart: "Начало",
    profileReviewEnd: "Конец",
    profileReviewPresent: "сейчас",
    profileReviewEducation: "Образование",
    profileReviewEducationEmpty: "Образования пока нет.",
    profileReviewEducationAdd: "Добавить образование",
    profileReviewEducationItem: (n) => `Образование #${n}`,
    profileReviewDegree: "Степень",
    profileReviewField: "Специальность",
    profileReviewSchool: "Школа / Университет",
    profileReviewEduYear: "Год",
    profileReviewLanguages: "Языки",
    profileReviewLanguagesEmpty: "Языков пока нет.",
    profileReviewLanguageAdd: "Добавить язык",
    profileReviewLangCode: "Язык",
    profileReviewLangLevel: "Уровень",
    profileReviewLangNative: "Родной",
    profileReviewLangLabel: (code) =>
      ({ az: "Азербайджанский", en: "Английский", ru: "Русский", tr: "Турецкий", de: "Немецкий", fr: "Французский" }[
        code
      ] || code),
    profileReviewLinks: "Ссылки",
    profileReviewLinkedin: "LinkedIn",
    profileReviewGithub: "GitHub",
    profileReviewPortfolio: "Портфолио / сайт",
    profileReviewContact: "Контакты",
    profileReviewFullName: "Имя",
    profileReviewCity: "Город",
    profileReviewCountry: "Страна",
    profileReviewStatusDraft: "Черновик",
    profileReviewStatusConfirmed: "Подтверждён",
    profileReviewConfidence: (n) => `Уверенность: ${Math.round(n * 100)}%`,
    profileReviewSave: "Сохранить",
    profileReviewConfirm: "Подтвердить профиль",
    profileReviewReset: "Сбросить",
    profileReviewResetConfirm: "Профиль будет полностью очищен. Можно снова загрузить CV или заполнить вручную. Продолжить?",
    profileReviewResetDone: "Профиль сброшен.",
    profileReviewResetError: "Не удалось сбросить профиль.",
    profileReviewSaved: "Профиль сохранён.",
    profileReviewConfirmed: "Профиль подтверждён.",
    profileReviewError: "Не удалось сохранить профиль.",
    profileReviewRolesTitle: "Подходящие роли",
    profileReviewRolesEmpty: "Пока нет предложений ролей. Добавьте навыки и сохраните.",
    profileReviewRolesConsent: "Включите согласие на matching, чтобы видеть предложения ролей.",
    profileReviewRolesConsentLink: "Настройки конфиденциальности",
    profileReviewRolesScore: (n) => `${Math.round(n * 100)}%`,
    recommendationsOpen: "Рекомендации",
    recommendationsTitle: "Рекомендации",
    recommendationsLede: "Выберите роль — чему учиться, что уже есть и подходящие вакансии.",
    recommendationsDisclaimer: "Скор правилный; при включении может добавляться AI-переранжирование и пояснения.",
    recommendationsGate: "Рекомендации доступны только кандидатам.",
    recommendationsConsent: "Включите согласие на matching, чтобы видеть рекомендации.",
    recommendationsConsentLink: "Настройки конфиденциальности",
    recommendationsRoles: "Подходящие роли",
    recommendationsSelectedRole: "Выбранная роль",
    recommendationsJobs: "Подходящие вакансии",
    recommendationsEmptyRoles: "Пока нет предложений ролей. Добавьте навыки в профиль.",
    recommendationsEmptyJobs: "Пока нет подходящих вакансий. Заполните профиль или загляните позже.",
    recommendationsScore: (n) => `${Math.round(n * 100)}%`,
    recommendationsUp: "Подходит",
    recommendationsDown: "Не подходит",
    recommendationsReason: "Причина",
    recommendationsReasonLocation: "Локация",
    recommendationsReasonSeniority: "Уровень",
    recommendationsReasonTechnology: "Технологии",
    recommendationsReasonSalary: "Зарплата",
    recommendationsGap: "Пробел в навыках",
    recommendationsGapEmpty: "Для этой роли пробел не рассчитан.",
    recommendationsGapLearn: "Изучить дальше",
    recommendationsGapShare: (pct) => `${pct}% доля`,
    recommendationsGapGrowth: (pct) => `${pct > 0 ? "+" : ""}${pct}% за неделю`,
    recommendationsGapGrowthSurge: "Резкий рост",
    recommendationsGapGrowthDrop: "Резкое снижение",
    recommendationsGapOftenWith: (base, pct) => `Требуется примерно в ${pct}% вакансий с ${base}`,
    recommendationsFeedbackSaved: "Отзыв сохранён.",
    recommendationsFeedbackError: "Не удалось сохранить отзыв.",
    recommendationsGapCourse: "Курс Academy",
    recommendationsGapCareerPath: "Карьерный путь Academy",
    recommendationsGapLink: "Пробел в навыках и курсы Academy",
    skillsOpen: "Навыки",
    skillsTitle: "Навыки и пробелы",
    skillsLede: "Выберите роль — что уже есть, чему учиться и курсы Academy.",
    skillsGate: "Анализ навыков доступен только кандидатам.",
    skillsTargetRole: "Целевая роль",
    skillsHave: "У вас есть",
    skillsMissing: "Не хватает",
    skillsHaveCount: (n) => `${n} есть`,
    skillsMissingCount: (n) => `${n} не хватает`,
    skillsHaveEmpty: "Для этой роли подтверждённых навыков нет.",
    skillsMissingEmpty: "Для этой роли недостающих навыков нет.",
    skillsCoachTitle: "Коуч по роли",
    skillsCoachMustLearn: "Учить в первую очередь",
    skillsCoachStrong: "Сильные стороны",
    skillsCoachTransferable: "Переносимые навыки",
    skillsCoachTransfer: (from, to) => `${from} → ${to}`,
    recommendationsCoachMore: "Полный совет коуча",
    insightsOpen: "Insights",
    insightsTitle: "Insights этой недели",
    insightsLede: "План обучения, почти подходящие вакансии и Academy — в одном месте.",
    insightsGate: "Для insights нужен аккаунт кандидата.",
    insightsCoachTitle: "Еженедельный план обучения",
    insightsCoachRole: (role) => `Роль: ${role}`,
    insightsCoachEmpty: "Плана коуча пока нет. Подтвердите профиль и включите согласие на matching.",
    insightsNearTitle: "Почти подходящие вакансии",
    insightsNearEmpty: "Пока нет почти подходящих вакансий.",
    insightsGrowthTitle: "Путь обучения",
    insightsGrowthEmpty: "Пока нет рекомендаций Academy или roadmap.",
    noticeCtaOpen: "Открыть",
    noticeCtaLearn: "Учить",
    noticeCtaInsights: "Insights",
    noticeCtaProfile: "Заполнить профиль",
    noticeRoadmapTitle: "Шаги обучения",
    noticeComingSoon: "Обучение Ingress скоро",
    emailSettingsOpen: "Настройки уведомлений",
    emailSettingsTitle: "Настройки уведомлений",
    emailSettingsLede: "Дайджесты, оповещения о совпадениях и push. Транзакционные письма отдельно.",
    emailSettingsGate: "Для настроек уведомлений нужен аккаунт кандидата.",
    emailSettingsPrivacyLink: "Конфиденциальность и согласия",
    emailSettingsConsentOff: "Согласие на маркетинговые письма выключено.",
    emailSettingsFrequency: "Частота",
    emailSettingsLanguage: "Язык писем",
    emailSettingsWeekday: "День отправки",
    emailSettingsDigest: "Еженедельный / двухнедельный дайджест",
    emailSettingsHighMatch: "Оповещения о сильных совпадениях",
    emailSettingsMatchNear: "Почти подходящие вакансии (рост навыков)",
    emailSettingsProfileNudge: "Напоминания заполнить профиль",
    emailSettingsCoachWeekly: "Еженедельный план обучения",
    emailSettingsPush: "Браузерные push-уведомления (master)",
    emailSettingsPushEnable: "Разрешить уведомления",
    emailSettingsPushDisable: "Удалить push-подписку",
    emailSettingsPushHint:
      "Нужны разрешение браузера и подписка. На iOS — только установленное PWA по HTTPS.",
    emailSettingsPushOn: "Браузерный push включён.",
    emailSettingsPushDenied: "Разрешение на уведомления отклонено. Включите в настройках браузера.",
    emailSettingsPushUnsupported: "Этот браузер не поддерживает Web Push.",
    emailSettingsPushVapid: "Push не настроен на сервере (VAPID).",
    emailSettingsPushError: "Не удалось подписаться на push.",
    emailSettingsSaved: "Настройки уведомлений сохранены.",
    emailSettingsError: "Не удалось сохранить настройки.",
    emailFreqWeekly: "Еженедельно",
    emailFreqBiweekly: "Раз в две недели",
    emailFreqImportant: "Только важное",
    emailFreqNone: "Ничего",
    emailWeekdayMon: "Понедельник",
    emailWeekdayTue: "Вторник",
    emailWeekdayWed: "Среда",
    emailWeekdayThu: "Четверг",
    emailWeekdayFri: "Пятница",
    emailWeekdaySat: "Суббота",
    emailWeekdaySun: "Воскресенье",
    unsubscribeTitle: "Отписка",
    unsubscribeLede: "Остановить маркетинговые и рекомендательные письма?",
    unsubscribeConfirm: "Отписаться",
    unsubscribeManage: "Управлять настройками почты",
    unsubscribeDone: "Вы отписаны. Транзакционные письма (например, статус отклика) могут отправляться.",
    unsubscribeInvalid: "Ссылка недействительна или устарела.",
    unsubscribeLoading: "Проверка…",
    notifications: "Уведомления",
    notificationsTitle: "Уведомления",
    notificationsEmpty: "Уведомлений нет.",
    notificationsGate: "Чтобы видеть уведомления, войдите в аккаунт.",
    notificationsUnread: (n) => `Уведомления, непрочитанных: ${n}`,
    markRead: "Прочитано",
    markAllRead: "Отметить все прочитанными",
    noteApplicationNew: (title) => `По объявлению «${title}» пришёл новый отклик.`,
    noteApplicationSeen: (title) => `Ваш отклик по объявлению «${title}» просмотрен.`,
    noteApplicationRejected: (title) => `Ваш отклик по объявлению «${title}» отклонён.`,
    noteAdApproved: (title) => `Объявление «${title}» одобрено.`,
    noteAdRejected: (title) => `Объявление «${title}» отклонено.`,
    noteAdReview: (title) => `Объявление «${title}» снова на модерации после правки.`,
    noteMatchNew: (title) => `Новое совпадение: «${title}».`,
    noteMatchNear: (title) => `Почти совпадение — прокачайте навык: «${title}».`,
    noteProfileNudge: () => "Заполните профиль — CV и навыки помогут найти совпадения.",
    noteCoachWeekly: () => "План обучения на эту неделю готов.",


  },
};

export function text(locale) {
  return copy[locale] || copy.az;
}

// Worker categories (worker/worker/techstack.py CATEGORIES), in this order.
export const CATEGORY_ORDER = [
  "Backend", "Frontend", "Full-stack", "Mobile", "DevOps/Cloud", "Data/ML",
  "QA", "Security", "Design/UX", "Product", "IT Support", "Other tech",
];

export const categoryNames = {
  az: {
    Backend: "Backend", Frontend: "Frontend", "Full-stack": "Full-stack", Mobile: "Mobil",
    "DevOps/Cloud": "DevOps / Bulud", "Data/ML": "Data / ML", QA: "QA / Test", Security: "Təhlükəsizlik",
    "Design/UX": "Dizayn / UX", Product: "Məhsul / Layihə", "IT Support": "IT dəstək", "Other tech": "Digər IT",
  },
  en: {
    Backend: "Backend", Frontend: "Frontend", "Full-stack": "Full-stack", Mobile: "Mobile",
    "DevOps/Cloud": "DevOps / Cloud", "Data/ML": "Data / ML", QA: "QA / Testing", Security: "Security",
    "Design/UX": "Design / UX", Product: "Product / Project", "IT Support": "IT support", "Other tech": "Other tech",
  },
  ru: {
    Backend: "Backend", Frontend: "Frontend", "Full-stack": "Full-stack", Mobile: "Мобильная разработка",
    "DevOps/Cloud": "DevOps / Облако", "Data/ML": "Data / ML", QA: "QA / Тестирование", Security: "Безопасность",
    "Design/UX": "Дизайн / UX", Product: "Продукт / Проект", "IT Support": "IT-поддержка", "Other tech": "Другое IT",
  },
};

export function categoryLabel(locale, name) {
  const names = categoryNames[locale] || categoryNames.az;
  return names[name] || name;
}

export const languageNames = {
  az: { az: "Azərbaycan", en: "İngilis", ru: "Rus", es: "İspan", uk: "Ukrayna", de: "Alman", fr: "Fransız", tr: "Türk", pt: "Portuqal" },
  en: { az: "Azerbaijani", en: "English", ru: "Russian", es: "Spanish", uk: "Ukrainian", de: "German", fr: "French", tr: "Turkish", pt: "Portuguese" },
  ru: { az: "Азербайджанский", en: "Английский", ru: "Русский", es: "Испанский", uk: "Украинский", de: "Немецкий", fr: "Французский", tr: "Турецкий", pt: "Португальский" },
};

export function languageLabel(locale, code) {
  const names = languageNames[locale] || languageNames.az;
  return names[code] || code;
}


export function hrefFor(locale, { mode = "browse", jobId, companySlug, skillId } = {}) {
  const base = locale === "az" ? "" : `/${locale}`;
  if (jobId) return `${base}/jobs/${jobId}`;
  if (companySlug) return `${base}/companies/${encodeURIComponent(companySlug)}`;
  if (mode === "companies") return `${base}/companies`;
  if (skillId != null && String(skillId).trim() !== "") {
    const skillPath = `${base}/trends/${encodeURIComponent(String(skillId).trim())}`;
    if (mode === "trendJobs") return `${skillPath}/jobs`;
    return skillPath;
  }
  if (mode === "trends" || mode === "trend") return `${base}/trends`;
  if (mode === "post") return `${base}/post`;
  if (mode === "company") return `${base}/company`;
  if (mode === "admin") return `${base}/admin`;
  if (mode === "applications") return `${base}/applications`;
  if (mode === "saved") return `${base}/saved`;
  if (mode === "talent") return `${base}/talent`;
  if (mode === "profile") return `${base}/profile`;
  if (mode === "profileReview") return `${base}/profile/review`;
  if (mode === "recommendations") return `${base}/me/recommendations`;
  if (mode === "skills") return `${base}/me/recommendations`;
  if (mode === "insights") return `${base}/me/insights`;
  if (mode === "emailSettings") return `${base}/settings/notifications`;
  if (mode === "notifications") return `${base}/notifications`;
  return base || "/";
}

export function academyCourseUrl(courseId) {
  const id = String(courseId || "").trim();
  if (!id) return "";
  const base = (process.env.NEXT_PUBLIC_ACADEMY_COURSE_BASE || "https://ingress.academy/courses/").replace(
    /\/?$/,
    "/",
  );
  return `${base}${encodeURIComponent(id)}`;
}
